"""
audio.py — Audio Test and Preview API Router

Endpoints:
    POST /api/audio/test               — Trigger a test audio push to a camera via go2rtc
    POST /api/audio/preview            — Generate a deterrent message sample and return
                                         raw WAV audio for in-browser playback
    POST /api/audio/test-tts-provider  — Validate cloud TTS provider credentials (no audio)

The test endpoint is intended for setup verification: it pushes a short test
tone or a canned message to a camera's speaker so the user can confirm the
audio path works without triggering a real detection event.

The preview endpoint synthesizes a deterrent message using the requested TTS
provider and persona, then streams the WAV back to the browser so the user
can hear what the combination sounds like without pushing anything to a
camera speaker.  This is a "try before you buy" feature for voice / persona
selection in the dashboard config UI.

For dispatch personas (``police_dispatch``, ``tony_montana_dispatch``), the
preview request is **proxied to the VoxWatch Preview API** (port 8892 by
default) so the full dispatch experience — channel intro, random chatter,
multi-segment TTS, radio effects, officer response — is generated by the same
code that runs during live detection events.  If the VoxWatch service is
unreachable the endpoint falls back to local synthesis so the user always
hears something.

WARNING: The test push calls go2rtc directly using the same mechanism as
VoxWatch. Ensure the camera speaker volume and message content are appropriate
before calling this endpoint.

Security:
    The camera_name field in the request body is validated against a strict
    allowlist pattern before use.  This prevents SSRF attacks where a crafted
    camera name could direct go2rtc to fetch audio from or push audio to an
    unintended internal host.  See the _validate_camera_name helper for details.
"""

import asyncio
import logging
import re
import tempfile
import time
from collections import defaultdict
from pathlib import Path
from typing import Optional

import aiohttp
from fastapi import APIRouter, HTTPException, UploadFile, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from backend.services import go2rtc_client as g2rtc_module
from backend.services.config_service import config_service

logger = logging.getLogger("dashboard.router.audio")

router = APIRouter(prefix="/audio", tags=["Audio"])

# ── Rate limiting ─────────────────────────────────────────────────────────────
# Simple in-memory rate limiter for the audio test endpoint.
# Prevents abuse (intentional or accidental) — pushing audio to camera speakers
# too frequently is annoying and could mask real deterrent events.
#
# Limit: 5 pushes per camera per 60 seconds.

_RATE_LIMIT_MAX = 5
_RATE_LIMIT_WINDOW = 60.0  # seconds
_push_timestamps: dict[str, list[float]] = defaultdict(list)


def _check_rate_limit(camera_name: str) -> None:
    """Enforce per-camera rate limit on audio test pushes.

    Tracks timestamps of recent pushes per camera and rejects requests
    that exceed the limit within the time window.

    Args:
        camera_name: Camera to check rate limit for.

    Raises:
        HTTPException 429: If rate limit exceeded.
    """
    now = time.monotonic()
    timestamps = _push_timestamps[camera_name]

    # Prune old entries outside the window
    _push_timestamps[camera_name] = [t for t in timestamps if now - t < _RATE_LIMIT_WINDOW]
    timestamps = _push_timestamps[camera_name]

    if len(timestamps) >= _RATE_LIMIT_MAX:
        raise HTTPException(
            status_code=429,
            detail=(
                f"Rate limit exceeded for camera '{camera_name}'. "
                f"Maximum {_RATE_LIMIT_MAX} test pushes per {int(_RATE_LIMIT_WINDOW)}s."
            ),
        )

    timestamps.append(now)

# ── Input validation ──────────────────────────────────────────────────────────
# Camera names must consist only of alphanumeric characters, underscores, and
# hyphens.  This is the same pattern enforced in cameras.py.
#
# Security rationale: request.camera_name is used to look up a go2rtc stream
# and construct URLs.  An unrestricted name (e.g. "cam/../admin" or
# "cam?inject=1") could be exploited to redirect go2rtc's internal HTTP client
# to unintended destinations (SSRF).
_CAMERA_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


def _validate_camera_name(camera_name: str) -> None:
    """Raise HTTP 400 if *camera_name* contains characters outside the safe set.

    Security rationale: camera names are interpolated into URLs sent to the
    go2rtc API.  Without validation a malicious caller could inject extra path
    segments or query parameters, turning this endpoint into an SSRF vector
    against internal services reachable from the VoxWatch container.

    Args:
        camera_name: The camera name string to validate.

    Raises:
        HTTPException 400: If the name contains any disallowed characters.
    """
    if not _CAMERA_NAME_RE.match(camera_name):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Invalid camera name {camera_name!r}. "
                "Camera names may only contain letters, digits, underscores, "
                "and hyphens (pattern: ^[a-zA-Z0-9_-]+$)."
            ),
        )


# ── Request/response models ───────────────────────────────────────────────────

class TestAudioRequest(BaseModel):
    """Request body for POST /api/audio/test."""

    camera_name: str = Field(
        description=(
            "Camera name to push test audio to (must match go2rtc stream name). "
            "Allowed characters: letters, digits, underscores, hyphens."
        )
    )
    message: str = Field(
        default="This is a VoxWatch audio system test.",
        description="Message text to synthesize and push (kept short for testing)",
        max_length=200,
    )
    audio_server_url: Optional[str] = Field(
        default=None,
        description=(
            "Base URL of the VoxWatch audio HTTP server "
            "(e.g. 'http://192.168.1.10:8891'). "
            "Used to construct the audio source URL for go2rtc. "
            "If not provided, uses a pre-generated test tone."
        ),
    )


class TestAudioResponse(BaseModel):
    """Response from POST /api/audio/test."""

    success: bool = Field(description="Whether go2rtc accepted the push request")
    camera: str = Field(description="Camera the test was sent to")
    stream_name: str = Field(description="go2rtc stream name used")
    message: str = Field(description="Human-readable status message")


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post(
    "/test",
    response_model=TestAudioResponse,
    summary="Trigger test audio push",
    description=(
        "Pushes a test audio stream to a camera speaker via go2rtc. "
        "Used to verify the audio pipeline is working without needing a real detection. "
        "Requires go2rtc to be reachable and the stream to be configured."
    ),
    status_code=status.HTTP_200_OK,
)
async def test_audio_push(request: TestAudioRequest) -> TestAudioResponse:
    """Trigger a test audio push to a camera via go2rtc.

    Looks up the camera's go2rtc stream name from config.yaml first, then
    falls back to querying go2rtc directly if the camera is not in VoxWatch
    config. This allows testing audio on any camera visible in go2rtc, not
    just cameras configured in VoxWatch.

    Note: This endpoint only sends the push request to go2rtc. Actual TTS
    generation requires the VoxWatch audio pipeline to be running. For a
    basic connectivity test, the audio_server_url can point to any accessible
    audio file.

    Args:
        request: TestAudioRequest with camera name, message, and optional URL.
                 camera_name is validated before use to prevent SSRF.

    Returns:
        TestAudioResponse indicating success or failure.

    Raises:
        400: If request.camera_name contains disallowed characters.
        404: If the camera is not found in config.yaml or go2rtc streams.
        503: If go2rtc is not reachable.
    """
    # Validate camera name and enforce rate limit before doing any real work.
    # go2rtc stream names (derived from camera names) are interpolated into
    # the /api/ffmpeg?dst=<name> query parameter — an unvalidated name could
    # inject additional query parameters or path segments.
    _validate_camera_name(request.camera_name)
    _check_rate_limit(request.camera_name)

    # Look up the go2rtc stream name.  Try VoxWatch config first (which may
    # map a Frigate camera name to a different go2rtc stream name), then fall
    # back to probing go2rtc directly so unconfigured cameras can still be
    # tested.
    stream_name = await _get_stream_name(request.camera_name)
    if stream_name is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"Camera {request.camera_name!r} not found in config.yaml or "
                "in the go2rtc stream list. "
                "Ensure the stream name matches the Frigate camera name."
            ),
        )

    if g2rtc_module.go2rtc_client is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="go2rtc client not initialized. Check go2rtc config in config.yaml.",
        )

    # Determine the audio source URL for go2rtc.
    # The VoxWatch container serves audio files on port 8891 (audio_push.serve_port).
    # We use the cached Stage 1 audio for testing since it's always available.
    cfg = await config_service.get_config()
    go2rtc_host = cfg.get("go2rtc", {}).get("host", "localhost")
    serve_port = cfg.get("audio_push", {}).get("serve_port", 8891)
    audio_url = f"http://{go2rtc_host}:{serve_port}/stage1_cached.wav"

    logger.info(
        "Test audio push: camera=%s stream=%s url=%s",
        request.camera_name,
        stream_name,
        audio_url,
    )

    # Warmup push — first push after idle establishes backchannel but
    # audio may not play. Send a short warmup file first.
    warmup_url = f"http://{go2rtc_host}:{serve_port}/warmup_silent.wav"
    await g2rtc_module.go2rtc_client.push_audio(stream_name, warmup_url)

    import asyncio
    await asyncio.sleep(2.0)

    # Real audio push
    success = await g2rtc_module.go2rtc_client.push_audio(stream_name, audio_url)

    return TestAudioResponse(
        success=success,
        camera=request.camera_name,
        stream_name=stream_name,
        message=(
            "Test audio push sent to go2rtc successfully. "
            "Check camera speaker in 1-3 seconds."
            if success
            else "go2rtc rejected the push request. Check stream name and go2rtc logs."
        ),
    )


# ── Announce endpoint ─────────────────────────────────────────────────────────
# Purpose-built TTS announcement endpoint for Home Assistant automations and
# external integrations.  Unlike the test endpoint, this does real TTS synthesis
# and supports custom voice, provider, speed, and attention tone settings.
#
# The dashboard proxies the request to the VoxWatch service's preview API
# (port 8892) which has access to the full AudioPipeline.


class AnnounceRequest(BaseModel):
    """Request body for POST /api/audio/announce."""

    camera: str = Field(
        description=(
            "Target camera name to play the announcement on. "
            "Must match a go2rtc stream name."
        )
    )
    message: str = Field(
        description="Text to synthesise and play on the camera speaker.",
        max_length=1000,
    )
    voice: Optional[str] = Field(
        default=None,
        description="TTS voice override. Uses configured default when omitted.",
    )
    provider: Optional[str] = Field(
        default=None,
        description="TTS provider override (kokoro, piper, elevenlabs, etc.).",
    )
    speed: Optional[float] = Field(
        default=None,
        description="Playback speed multiplier (0.25–4.0).",
        ge=0.25,
        le=4.0,
    )
    tone: Optional[str] = Field(
        default=None,
        description="Attention tone to prepend: 'short', 'long', 'siren', or 'none'.",
    )


class AnnounceResponse(BaseModel):
    """Response from POST /api/audio/announce."""

    success: bool = Field(description="Whether the announcement was played")
    camera: str = Field(description="Camera the announcement was sent to")
    duration_ms: Optional[int] = Field(
        default=None,
        description="Total processing time in milliseconds",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the announcement failed",
    )


@router.post(
    "/announce",
    response_model=AnnounceResponse,
    summary="Play a TTS announcement on a camera speaker",
    description=(
        "Synthesises text-to-speech and plays it on a camera speaker via go2rtc. "
        "Designed for Home Assistant automations and external integrations. "
        "Supports custom voice, provider, speed, and attention tone settings."
    ),
    status_code=status.HTTP_200_OK,
)
async def announce(request: AnnounceRequest) -> AnnounceResponse:
    """Play a TTS announcement on a camera speaker.

    Proxies the request to the VoxWatch service's preview API which has
    access to the full AudioPipeline for TTS generation, codec conversion,
    and go2rtc push.

    Args:
        request: AnnounceRequest with camera, message, and optional overrides.

    Returns:
        AnnounceResponse with success status and timing.
    """
    _validate_camera_name(request.camera)

    # Build the payload for the VoxWatch announce API.
    payload: dict = {
        "camera": request.camera,
        "message": request.message,
    }
    if request.voice is not None:
        payload["voice"] = request.voice
    if request.provider is not None:
        payload["provider"] = request.provider
    if request.speed is not None:
        payload["speed"] = request.speed
    if request.tone is not None:
        payload["tone"] = request.tone

    # Resolve the VoxWatch service preview API URL.
    cfg = await config_service.get_config()
    go2rtc_host = cfg.get("go2rtc", {}).get("host", "localhost")
    preview_port = cfg.get("preview_api_port", 8892)
    announce_url = f"http://{go2rtc_host}:{preview_port}/api/announce"

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                announce_url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=60),
            ) as resp:
                result = await resp.json()

                if resp.status == 200 and result.get("success"):
                    return AnnounceResponse(
                        success=True,
                        camera=request.camera,
                        duration_ms=result.get("duration_ms"),
                    )
                else:
                    error_msg = result.get("error", f"VoxWatch API returned HTTP {resp.status}")
                    logger.error(
                        "Announce failed for camera %s: %s",
                        request.camera,
                        error_msg,
                    )
                    return AnnounceResponse(
                        success=False,
                        camera=request.camera,
                        error=error_msg,
                    )
    except aiohttp.ClientError as exc:
        logger.error("Announce: VoxWatch service unreachable: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "VoxWatch service is not reachable. "
                "Ensure the VoxWatch container is running."
            ),
        ) from exc


# ── Preview endpoint ──────────────────────────────────────────────────────────

# Sample scene description used when the caller does not supply a custom message.
# Realistic enough that the user hears what an actual deterrent would sound like.
_SAMPLE_SCENE = (
    "Male in a dark hoodie approaching from the driveway at 10:47 PM, "
    "carrying a backpack, looking toward the front door."
)

# Persona-specific sample messages — one pre-written deterrent per persona so the
# preview sounds realistic without needing a live AI call.
_PERSONA_SAMPLES: dict[str, str] = {
    "standard": (
        "This is the Standard response mode. "
        "Attention. Person in a dark jacket near the side gate. "
        "You are being recorded on camera. Leave the property immediately."
    ),
    "live_operator": (
        "This is the Live Operator response mode. "
        "I can see you at the front door. Step away from the property now."
    ),
    "private_security": (
        "This is the Private Security response mode. "
        "Attention. You are on private property. This area is under 24 hour surveillance. "
        "Leave immediately or authorities will be contacted."
    ),
    "recorded_evidence": (
        "This is the Recorded Evidence response mode. "
        "Subject recorded. Facial capture complete. Entry attempt logged. "
        "Footage has been transmitted to secure storage."
    ),
    "homeowner": (
        "This is the Homeowner response mode. "
        "Hey. I can see you on camera. I don't know who you are, but you need to leave. Now."
    ),
    "automated_surveillance": (
        "This is the Automated Surveillance response mode. "
        "Movement detected. Perimeter zone three. Behavior flagged. "
        "Escalating monitoring level."
    ),
    "mafioso": (
        "This is the Italian Mafioso response mode. "
        "Hey pal, I see you over there in that jacket. "
        "You think you can just walk up to my place like that? Get lost, before things get complicated."
    ),
    "drill_sergeant": (
        "This is the Drill Sergeant response mode. "
        "YOU! By the gate! Drop what you're carrying and vacate this area immediately! "
        "You have ten seconds! Move it!"
    ),
    "british_butler": (
        "This is the British Butler response mode. "
        "I beg your pardon, but one does not simply approach the premises uninvited. "
        "I must insist you remove yourself at once."
    ),
    "southern_sheriff": (
        "This is the Southern Sheriff response mode. "
        "Well now, I reckon you might be at the wrong house tonight. "
        "I can see you real clear on camera, so why don't you just move along."
    ),
    "ai_overlord": (
        "This is the AI Overlord response mode. "
        "Subject identified. Dark garment. Driveway approach vector. "
        "Tracking movement pattern. Law enforcement notification queued."
    ),
    "disappointed_parent": (
        "This is the Disappointed Parent response mode. "
        "Really? Sneaking around at this hour? "
        "I can see you perfectly on camera. I expected better. Go home."
    ),
    "pirate_captain": (
        "This is the Pirate Captain response mode. "
        "Arrr! What scallywag dares approach me vessel? "
        "I see ye clear as day! Best be sailing away before I sound the alarm!"
    ),
    "tony_montana": (
        "This is the Tony Montana response mode. "
        "You wanna play rough? Okay! I see you right there. "
        "You picked the wrong house, my friend. This is MY house!"
    ),
    "police_dispatch": (
        "This is the Police Dispatch response mode. "
        "All units... ten ninety-seven at the residence. "
        "Subject... dark clothing, medium build. "
        "Nearest unit, respond... code three."
    ),
    "neighborhood_watch": (
        "This is the Neighborhood Watch response mode. "
        "Attention, this is a neighborhood watch advisory. "
        "An unidentified individual has been observed approaching this property. "
        "Community patrol and local authorities have been notified."
    ),
    "guard_dog": (
        "This is the Guard Dog Warning response mode. "
        "Hey. I see you on camera. Just so you know, the dogs haven't been fed yet today. "
        "I can let them out if you'd like to stay."
    ),
}

# Default message used when no persona match is found (catches custom personas).
_DEFAULT_SAMPLE = (
    "This is a custom response mode preview. "
    "Attention. This property is under active surveillance. "
    "You have been identified on camera. Please leave the area immediately."
)


class PreviewRequest(BaseModel):
    """Request body for POST /api/audio/preview."""

    persona: str = Field(
        default="standard",
        description="Persona name from the PERSONAS dict (e.g. 'mafioso', 'drill_sergeant').",
    )
    voice: str = Field(
        default="af_heart",
        description="TTS voice identifier (Kokoro voice ID, Piper model name, etc.).",
    )
    provider: str = Field(
        default="kokoro",
        description="TTS provider name: 'kokoro', 'piper', 'espeak'.",
    )
    provider_host: Optional[str] = Field(
        default=None,
        description=(
            "Base URL of the remote TTS server (e.g. 'http://kokoro-server:8880'). "
            "Required for Kokoro remote. Ignored for piper/espeak."
        ),
    )
    message: Optional[str] = Field(
        default=None,
        description=(
            "Custom message text to synthesize. "
            "If omitted a realistic deterrent sample is generated from the persona."
        ),
        max_length=500,
    )
    speed: float = Field(
        default=1.0,
        description="Playback speed multiplier (0.5 – 2.0).",
        ge=0.25,
        le=4.0,
    )


def _normalize_dispatch_for_tts(text: str) -> str:
    """Normalize dispatch text for natural TTS pronunciation.

    Converts 10-codes to spoken form and expands address numbers
    digit-by-digit, matching how real dispatchers speak.

    Args:
        text: Raw dispatch text.

    Returns:
        Normalized text ready for TTS.
    """
    import re

    # 10-code replacements
    ten_codes = {
        "10-4": "ten four", "10-15": "ten fifteen", "10-20": "ten twenty",
        "10-29": "ten twenty-nine", "10-31": "ten thirty-one",
        "10-70": "ten seventy", "10-97": "ten ninety-seven",
    }
    result = text
    for code, spoken in ten_codes.items():
        result = result.replace(code, spoken)
    result = result.replace("Code 3", "code three")
    result = result.replace("code 3", "code three")

    # Expand address numbers (3+ digits before a capitalized word)
    digit_words = {
        "0": "zero", "1": "one", "2": "two", "3": "three", "4": "four",
        "5": "five", "6": "six", "7": "seven", "8": "eight", "9": "nine",
    }

    def expand_digits(match: re.Match) -> str:
        words = " ".join(digit_words[d] for d in match.group(1))
        return words + match.group(2)

    result = re.sub(r'\b(\d{3,})\b(\s+[A-Z])', expand_digits, result)
    return result


async def _personalize_dispatch_sample(message: str) -> str:
    """Replace generic dispatch sample text with configured address/agency.

    Reads the saved config for dispatch settings and injects them into
    the sample message so the preview sounds like the real thing.

    Args:
        message: The dispatch sample text.

    Returns:
        Personalized message with address/agency if configured.
    """
    try:
        cfg = await config_service.get_raw_config()
        rm = cfg.get("response_mode", cfg.get("persona", {}))
        dispatch = rm.get("dispatch", {})

        address = dispatch.get("full_address", "").strip()
        agency = dispatch.get("agency", "").strip()
        callsign = dispatch.get("callsign", "").strip()

        if address:
            # Build a personalized sample
            agency_prefix = f"{agency} dispatch. " if agency else ""
            callsign_suffix = f" {callsign}, respond code 3." if callsign else " Requesting unit respond."
            return (
                f"{agency_prefix}All units, 10-31 in progress at {address}. "
                f"Suspect described as male, dark hoodie, carrying backpack, "
                f"approaching front entrance.{callsign_suffix} "
                f"Subject is on camera."
            )
    except Exception:
        pass
    return message


def _sample_for_persona(persona: str) -> str:
    """Return a realistic deterrent sample message for the given persona name.

    Prefers the exact persona key.  Falls back to the generic default so
    custom persona names don't blow up.

    Args:
        persona: Persona key string (e.g. "mafioso", "drill_sergeant").

    Returns:
        Sample deterrent message string, ready to pass to a TTS provider.
    """
    return _PERSONA_SAMPLES.get(persona, _DEFAULT_SAMPLE)


async def _synthesize_kokoro(
    message: str,
    voice: str,
    speed: float,
    host: str,
    output_path: str,
) -> None:
    """POST to a Kokoro TTS HTTP server and write the WAV response to disk.

    Kokoro's /tts endpoint accepts a JSON body and returns raw PCM/WAV audio.
    The VoxWatch kokoro_provider.py uses the same protocol — this function
    replicates that call so the preview endpoint doesn't need to import the
    full TTS provider machinery.

    Args:
        message:     Text to synthesize.
        voice:       Kokoro voice ID (e.g. "af_heart").
        speed:       Playback speed multiplier.
        host:        Base URL of the Kokoro HTTP server.
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 502: If the Kokoro server is unreachable or returns an error.
    """
    url = f"{host.rstrip('/')}/tts"
    payload = {"text": message, "voice": voice, "speed": speed}

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise HTTPException(
                        status_code=status.HTTP_502_BAD_GATEWAY,
                        detail=(
                            f"Kokoro server returned HTTP {resp.status}: {body[:200]}"
                        ),
                    )
                audio_bytes = await resp.read()

        Path(output_path).write_bytes(audio_bytes)

    except aiohttp.ClientError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Cannot reach Kokoro server at {host}: {exc}",
        ) from exc


async def _synthesize_piper(
    message: str,
    model: str,
    speed: float,
    output_path: str,
) -> None:
    """Run piper TTS via subprocess and write the WAV output to disk.

    Piper is invoked as ``piper --model <model> --output_file <path>`` with the
    message piped through stdin.  The model baked into the Docker image is used;
    the ``model`` argument is passed as-is so the preview respects whatever model
    the user has configured.

    Args:
        message:     Text to synthesize.
        model:       Piper model name (e.g. "en_US-lessac-medium").
        speed:       Length scale (1.0 = normal; piper uses length_scale inverse).
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 500: If piper exits with a non-zero return code.
        HTTPException 503: If the piper binary is not found.
    """
    # piper uses --length_scale as the inverse of speed: 1/speed gives the
    # correct duration scaling.  Clamp to avoid extreme values.
    length_scale = round(1.0 / max(speed, 0.25), 3)
    cmd = [
        "piper",
        "--model", model,
        "--length_scale", str(length_scale),
        "--output_file", output_path,
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await asyncio.wait_for(
            proc.communicate(input=message.encode()),
            timeout=30.0,
        )

        if proc.returncode != 0:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"piper exited with code {proc.returncode}: {stderr.decode()[:300]}",
            )

    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="piper binary not found. Ensure piper is installed in the Docker image.",
        )
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="piper synthesis timed out after 30 seconds.",
        )


async def _synthesize_espeak(
    message: str,
    speed: int,
    pitch: int,
    output_path: str,
) -> None:
    """Run espeak-ng via subprocess and write the WAV output to disk.

    espeak-ng is the always-available last-resort fallback.  It is invoked
    as ``espeak-ng -s <speed> -p <pitch> -w <output_path>`` with the message
    passed as the final argument.

    Args:
        message:     Text to synthesize.
        speed:       Words-per-minute rate (80 – 450).
        pitch:       Voice pitch (0 – 99).
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 503: If espeak-ng is not installed.
        HTTPException 500: On subprocess failure.
    """
    cmd = [
        "espeak-ng",
        "-s", str(speed),
        "-p", str(pitch),
        "-w", output_path,
        message,
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await asyncio.wait_for(
            proc.communicate(),
            timeout=15.0,
        )

        if proc.returncode != 0:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"espeak-ng exited with code {proc.returncode}: {stderr.decode()[:300]}",
            )

    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="espeak-ng binary not found. Install espeak-ng in the Docker image.",
        )
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="espeak-ng synthesis timed out after 15 seconds.",
        )


async def _resolve_cloud_tts_key(key_name: str) -> str:
    """Resolve a cloud TTS API key from the saved config.

    Reads the flat TTS config (e.g. tts.elevenlabs_api_key) and resolves
    ${ENV_VAR} tokens to actual values.

    Args:
        key_name: The flat config key name (e.g. "elevenlabs_api_key").

    Returns:
        The resolved API key, or empty string if not found.
    """
    import os
    import re
    try:
        raw_cfg = await config_service.get_raw_config()
        tts = raw_cfg.get("tts", {})
        val = tts.get(key_name, "")
        if not val or not isinstance(val, str):
            return ""
        env_match = re.match(r"\$\{(\w+)\}", val)
        if env_match:
            return os.environ.get(env_match.group(1), "")
        if val.startswith("***"):
            return ""
        return val
    except Exception:
        return ""


async def _synthesize_elevenlabs(
    message: str, api_key: str, voice_id: str, model: str, output_path: str,
) -> None:
    """Synthesize audio using ElevenLabs API via raw HTTP.

    No SDK required — uses aiohttp to POST to the text-to-speech endpoint
    and saves the returned audio bytes.

    Args:
        message: Text to synthesize.
        api_key: ElevenLabs API key.
        voice_id: Voice ID from ElevenLabs voice library.
        model: Model name (e.g. "eleven_flash_v2_5").
        output_path: Where to write the output audio file.
    """
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "audio/mpeg",
    }
    payload = {
        "text": message,
        "model_id": model,
        # High stability = monotone, flat delivery (how real dispatchers sound).
        # Low similarity_boost = less voice cloning artifacts.
        # style = 0 removes expressive/emotional inflection entirely.
        "voice_settings": {
            "stability": 1.0,
            "similarity_boost": 0.3,
            "style": 0.0,
            "use_speaker_boost": False,
        },
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status == 401:
                raise HTTPException(status_code=400, detail="Invalid ElevenLabs API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"ElevenLabs error: {body[:200]}")
            audio_data = await resp.read()

    # ElevenLabs returns MP3 — convert to WAV for browser playback
    proc = await asyncio.create_subprocess_exec(
        "ffmpeg", "-y", "-i", "pipe:0", "-f", "wav", output_path,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
    )
    await proc.communicate(input=audio_data)


async def _synthesize_openai_tts(
    message: str, api_key: str, voice: str, model: str, speed: float,
    output_path: str,
) -> None:
    """Synthesize audio using OpenAI TTS API via raw HTTP.

    Args:
        message: Text to synthesize.
        api_key: OpenAI API key.
        voice: Voice name (alloy, echo, fable, onyx, nova, shimmer).
        model: Model (tts-1 or tts-1-hd).
        speed: Speed multiplier (0.25-4.0).
        output_path: Where to write the output audio file.
    """
    url = "https://api.openai.com/v1/audio/speech"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "input": message,
        "voice": voice,
        "speed": max(0.25, min(4.0, speed)),
        "response_format": "wav",
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status == 401:
                raise HTTPException(status_code=400, detail="Invalid OpenAI API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"OpenAI TTS error: {body[:200]}")
            audio_data = await resp.read()

    with open(output_path, "wb") as f:
        f.write(audio_data)


async def _synthesize_cartesia(
    message: str, api_key: str, voice_id: str, output_path: str,
) -> None:
    """Synthesize audio using Cartesia Sonic API via raw HTTP.

    Args:
        message: Text to synthesize.
        api_key: Cartesia API key.
        voice_id: Cartesia voice ID.
        output_path: Where to write the output audio file.
    """
    url = "https://api.cartesia.ai/tts/bytes"
    headers = {
        "X-API-Key": api_key,
        "Cartesia-Version": "2024-06-10",
        "Content-Type": "application/json",
    }
    payload = {
        "transcript": message,
        "model_id": "sonic-english",
        "voice": {"mode": "id", "id": voice_id} if voice_id else {"mode": "id", "id": "a0e99841-438c-4a64-b679-ae501e7d6091"},
        "output_format": {"container": "wav", "encoding": "pcm_f32le", "sample_rate": 44100},
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status in (401, 403):
                raise HTTPException(status_code=400, detail="Invalid Cartesia API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"Cartesia error: {body[:200]}")
            audio_data = await resp.read()

    with open(output_path, "wb") as f:
        f.write(audio_data)


# ── VoxWatch Preview API proxy ────────────────────────────────────────────────
#
# Dispatch modes (police_dispatch, tony_montana_dispatch) require the full
# VoxWatch pipeline: channel intro, random chatter, multi-segment TTS, radio
# effects, and officer response.  All of that code lives in the VoxWatch
# service, not the dashboard.  Instead of duplicating it here we proxy the
# request to the VoxWatch Preview API running on port 8892.
#
# The dashboard itself has no VoxWatch port in its own config — we read the
# host from the go2rtc config (same host as the VoxWatch service) and the port
# from ``preview_api_port`` (defaulting to 8892).

#: Response modes that route through the VoxWatch Preview API.
#: Mirrors DISPATCH_MODES in voxwatch/radio_dispatch.py.
_DISPATCH_MODES: frozenset[str] = frozenset({"police_dispatch", "tony_montana_dispatch"})

#: Timeout (seconds) for the VoxWatch preview proxy call.
#: Dispatch previews can take 5-10 s (multiple TTS round-trips + ffmpeg concat).
_VOXWATCH_PROXY_TIMEOUT = 60.0


async def _get_voxwatch_preview_url() -> str:
    """Build the VoxWatch Preview API URL from saved config.

    Reads ``go2rtc.host`` for the hostname (VoxWatch and go2rtc typically run
    on the same host) and ``preview_api_port`` for the port (default 8892).

    Returns:
        Full URL string, e.g. ``"http://192.168.1.10:8892/api/preview"``.
    """
    try:
        cfg = await config_service.get_config()
        host: str = cfg.get("go2rtc", {}).get("host", "localhost")
        port: int = int(cfg.get("preview_api_port", 8892))
    except Exception:
        host = "localhost"
        port = 8892
    return f"http://{host}:{port}/api/preview"


async def _proxy_dispatch_preview(
    request: "PreviewRequest",
) -> Optional[tuple[bytes, dict[str, str]]]:
    """Proxy a preview request to the VoxWatch Preview API.

    Forwards the preview request body to the VoxWatch service on port 8892 and
    returns the raw WAV bytes along with provider tracking headers from the
    VoxWatch response.

    Args:
        request: The dashboard ``PreviewRequest`` model populated by the browser.

    Returns:
        Tuple of (wav_bytes, headers_dict) from the VoxWatch Preview API, or
        ``None`` if the request could not be completed.
    """
    url = await _get_voxwatch_preview_url()

    payload: dict = {
        "response_mode": request.persona,
        "voice": request.voice,
        "provider": request.provider,
        "speed": request.speed,
    }
    if request.message:
        payload["message"] = request.message

    logger.debug(
        "Proxying preview to VoxWatch Preview API: %s mode=%s provider=%s",
        url,
        request.persona,
        request.provider,
    )

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=_VOXWATCH_PROXY_TIMEOUT),
            ) as resp:
                if resp.status != 200:
                    body_text = await resp.text()
                    logger.warning(
                        "VoxWatch Preview API returned HTTP %d for preview: %s",
                        resp.status,
                        body_text[:200],
                    )
                    return None

                # Forward provider tracking headers from VoxWatch.
                proxy_headers = {
                    "X-Generation-Time-Ms": resp.headers.get("X-Generation-Time-Ms", "0"),
                    "X-TTS-Provider": resp.headers.get("X-TTS-Provider", request.provider),
                    "X-TTS-Configured": resp.headers.get("X-TTS-Configured", request.provider),
                    "X-TTS-Fallback": resp.headers.get("X-TTS-Fallback", "false"),
                }
                elapsed_ms = proxy_headers["X-Generation-Time-Ms"]
                logger.info(
                    "Preview received from VoxWatch: %s ms, mode=%s provider=%s",
                    elapsed_ms,
                    request.persona,
                    proxy_headers["X-TTS-Provider"],
                )
                wav_bytes = await resp.read()
                return (wav_bytes, proxy_headers)

    except aiohttp.ClientConnectorError as exc:
        logger.info(
            "VoxWatch Preview API unreachable at %s (%s) — falling back to local synthesis.",
            url,
            exc,
        )
        return None
    except asyncio.TimeoutError:
        logger.warning(
            "VoxWatch Preview API timed out after %.0fs — falling back to local synthesis.",
            _VOXWATCH_PROXY_TIMEOUT,
        )
        return None
    except Exception as exc:
        logger.warning(
            "VoxWatch Preview API proxy error: %s — falling back to local synthesis.",
            exc,
        )
        return None


@router.post(
    "/preview",
    summary="Generate browser-playable audio preview",
    description=(
        "Synthesizes a deterrent message using the specified TTS provider and persona, "
        "then returns the raw WAV audio for in-browser playback. "
        "No camera speaker is involved — this is a pure preview for voice selection. "
        "Supported providers: kokoro (remote HTTP server), piper (local), espeak (local fallback). "
        "Response headers X-TTS-Provider, X-TTS-Configured, and X-TTS-Fallback indicate which "
        "provider actually generated the audio and whether a fallback occurred."
    ),
    response_class=StreamingResponse,
    responses={
        200: {
            "content": {"audio/wav": {}},
            "description": "Raw WAV audio. Play with: new Audio(URL.createObjectURL(blob))",
            "headers": {
                "X-Generation-Time": {
                    "description": "Synthesis latency in milliseconds",
                    "schema": {"type": "string"},
                },
                "X-TTS-Provider": {
                    "description": "TTS provider that actually generated the audio",
                    "schema": {"type": "string"},
                },
                "X-TTS-Configured": {
                    "description": "TTS provider that was requested/configured",
                    "schema": {"type": "string"},
                },
                "X-TTS-Fallback": {
                    "description": "Whether a fallback provider was used ('true' or 'false')",
                    "schema": {"type": "string"},
                },
            },
        },
        400: {"description": "Unsupported provider or bad request"},
        502: {"description": "Remote TTS server error"},
        503: {"description": "Local TTS binary not available"},
    },
)
async def preview_audio(request: PreviewRequest) -> StreamingResponse:
    """Synthesize a deterrent message sample and stream WAV back to the browser.

    The caller selects a persona and TTS provider.  If no custom message is
    supplied, a pre-written sample for that persona is used so the user hears
    a realistic deterrent rather than a bland test phrase.

    Synthesis is performed inside a temporary file so the WAV can be read back
    after the subprocess/HTTP call finishes.  The temp file is deleted after
    the response is streamed.

    For cloud providers (ElevenLabs, OpenAI, Cartesia), if synthesis fails due
    to a missing or invalid API key, the endpoint falls back to espeak rather
    than returning an error, so the user always hears something.  The response
    headers X-TTS-Provider, X-TTS-Configured, and X-TTS-Fallback communicate
    what actually happened so the frontend can surface a warning if needed.

    Args:
        request: PreviewRequest with persona, voice, provider, optional message,
                 and speed.

    Returns:
        StreamingResponse with Content-Type audio/wav and headers:
        - X-Generation-Time: synthesis latency in milliseconds.
        - X-TTS-Provider: provider that actually generated the audio.
        - X-TTS-Configured: provider that was requested/configured.
        - X-TTS-Fallback: "true" if a fallback provider was used, "false" otherwise.

    Raises:
        400: If provider is unsupported (cloud providers that need full factory machinery).
        502: If the remote Kokoro server is unreachable or returns an error.
        503: If a required local binary (piper, espeak-ng) is not installed.
        504: If synthesis exceeds the timeout.
    """
    # Track which provider was requested and which actually ran, so the headers
    # can accurately reflect whether a fallback occurred.
    configured_provider = request.provider.lower()
    actual_provider = configured_provider
    used_fallback = False

    # ── Proxy to VoxWatch Preview API when needed ────────────────────────────
    # ALL preview requests proxy to the VoxWatch service first.  The
    # dashboard container has no TTS binaries (no espeak, piper, ffmpeg) —
    # only the VoxWatch container has the full AudioPipeline.  Cloud-only
    # providers (ElevenLabs, OpenAI, Cartesia) could technically run here
    # but routing everything through one path keeps voice resolution and
    # fallback behavior consistent.  If VoxWatch is unreachable, we fall
    # through to local cloud-only synthesis as a last resort.
    _should_proxy = True
    if _should_proxy:
        t_proxy_start = time.monotonic()
        proxy_result = await _proxy_dispatch_preview(request)
        if proxy_result is not None:
            wav_bytes, proxy_headers = proxy_result
            elapsed_ms = int((time.monotonic() - t_proxy_start) * 1000)
            logger.info(
                "Preview proxied from VoxWatch: persona=%s provider=%s fallback=%s elapsed_ms=%d bytes=%d",
                request.persona,
                proxy_headers.get("X-TTS-Provider", "?"),
                proxy_headers.get("X-TTS-Fallback", "false"),
                elapsed_ms,
                len(wav_bytes),
            )
            return StreamingResponse(
                content=iter([wav_bytes]),
                media_type="audio/wav",
                headers={
                    "X-Generation-Time": str(elapsed_ms),
                    "X-TTS-Provider": proxy_headers.get("X-TTS-Provider", configured_provider),
                    "X-TTS-Configured": proxy_headers.get("X-TTS-Configured", configured_provider),
                    "X-TTS-Fallback": proxy_headers.get("X-TTS-Fallback", "false"),
                    "Cache-Control": "no-store",
                },
            )
        # VoxWatch unreachable — fall through to local synthesis so the user
        # still hears something (plain TTS without the full dispatch experience).
        logger.info(
            "Dispatch preview falling back to local synthesis for persona=%s",
            request.persona,
        )

    # Resolve the message — prefer the caller's custom text, then persona sample.
    message = (request.message or "").strip() or _sample_for_persona(request.persona)

    # For dispatch personas that fell back to local synthesis, personalize with
    # configured address/agency and normalize 10-codes to spoken form for TTS.
    if request.persona in _DISPATCH_MODES:
        message = await _personalize_dispatch_sample(message)
        message = _normalize_dispatch_for_tts(message)

    t_start = time.monotonic()

    # Use a temp file for the WAV output.  The file is created here and cleaned
    # up after we read it back; NamedTemporaryFile with delete=False is used so
    # the subprocess can write to it by path on all platforms.
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        provider = request.provider.lower()

        if provider == "kokoro":
            # Kokoro requires a host URL.  Fall back to reading from config if
            # the caller didn't supply one (so users who have it saved in config
            # don't need to re-enter it).
            host = request.provider_host
            if not host:
                try:
                    cfg = await config_service.get_config()
                    host = cfg.get("tts", {}).get("kokoro_host") or None
                except Exception:
                    host = None

            if not host:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=(
                        "Kokoro host URL is required for preview. "
                        "Set it in TTS config or pass provider_host in the request."
                    ),
                )

            await _synthesize_kokoro(
                message=message,
                voice=request.voice,
                speed=request.speed,
                host=host,
                output_path=tmp_path,
            )

        elif provider == "piper":
            # voice field doubles as the model name for piper.
            # Piper runs inside the VoxWatch container, not the dashboard.
            # If piper isn't available here, fall back to espeak for preview.
            model = request.voice or "en_US-lessac-medium"
            try:
                await _synthesize_piper(
                    message=message,
                    model=model,
                    speed=request.speed,
                    output_path=tmp_path,
                )
            except HTTPException as exc:
                if exc.status_code == 503:
                    # Piper not installed in this container — use espeak fallback
                    logger.info(
                        "Piper not available in dashboard container, "
                        "falling back to espeak for preview"
                    )
                    actual_provider = "espeak"
                    used_fallback = True
                    wpm = int(min(450, max(80, 175 * request.speed)))
                    await _synthesize_espeak(
                        message=message,
                        speed=wpm,
                        pitch=50,
                        output_path=tmp_path,
                    )
                else:
                    raise

        elif provider == "espeak":
            # Speed for espeak is words-per-minute, not a multiplier.
            # Convert: 1.0 = 175 WPM (piper/kokoro normal), scale linearly.
            wpm = int(min(450, max(80, 175 * request.speed)))
            await _synthesize_espeak(
                message=message,
                speed=wpm,
                pitch=50,
                output_path=tmp_path,
            )

        elif provider == "elevenlabs":
            # Attempt ElevenLabs synthesis.  If the API key is missing or the
            # call fails, fall back to espeak so the user hears something and
            # the headers explain what happened.
            api_key = await _resolve_cloud_tts_key("elevenlabs_api_key")
            if not api_key:
                logger.warning(
                    "ElevenLabs API key not configured — falling back to espeak for preview. "
                    "Set tts.elevenlabs_api_key in config.yaml to enable ElevenLabs preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                try:
                    await _synthesize_elevenlabs(
                        message=message,
                        api_key=api_key,
                        voice_id=request.voice or "pNInz6obpgDQGcFmaJgB",
                        model="eleven_flash_v2_5",
                        output_path=tmp_path,
                    )
                except HTTPException as exc:
                    # API key invalid or ElevenLabs returned an error — fall back to
                    # espeak so the preview still works and the user can hear something.
                    logger.warning(
                        "ElevenLabs synthesis failed (HTTP %d: %s) — "
                        "falling back to espeak for preview.",
                        exc.status_code,
                        exc.detail,
                    )
                    actual_provider = "espeak"
                    used_fallback = True
                    wpm = int(min(450, max(80, 175 * request.speed)))
                    await _synthesize_espeak(
                        message=message,
                        speed=wpm,
                        pitch=50,
                        output_path=tmp_path,
                    )

        elif provider == "openai":
            # Same fallback pattern as ElevenLabs.
            api_key = await _resolve_cloud_tts_key("openai_api_key")
            if not api_key:
                logger.warning(
                    "OpenAI API key not configured — falling back to espeak for preview. "
                    "Set tts.openai_api_key in config.yaml to enable OpenAI TTS preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                try:
                    await _synthesize_openai_tts(
                        message=message,
                        api_key=api_key,
                        voice=request.voice or "onyx",
                        model="tts-1",
                        speed=request.speed,
                        output_path=tmp_path,
                    )
                except HTTPException as exc:
                    logger.warning(
                        "OpenAI TTS synthesis failed (HTTP %d: %s) — "
                        "falling back to espeak for preview.",
                        exc.status_code,
                        exc.detail,
                    )
                    actual_provider = "espeak"
                    used_fallback = True
                    wpm = int(min(450, max(80, 175 * request.speed)))
                    await _synthesize_espeak(
                        message=message,
                        speed=wpm,
                        pitch=50,
                        output_path=tmp_path,
                    )

        elif provider == "cartesia":
            # Same fallback pattern as ElevenLabs.
            api_key = await _resolve_cloud_tts_key("cartesia_api_key")
            if not api_key:
                logger.warning(
                    "Cartesia API key not configured — falling back to espeak for preview. "
                    "Set tts.cartesia_api_key in config.yaml to enable Cartesia preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                try:
                    await _synthesize_cartesia(
                        message=message,
                        api_key=api_key,
                        voice_id=request.voice or "",
                        output_path=tmp_path,
                    )
                except HTTPException as exc:
                    logger.warning(
                        "Cartesia synthesis failed (HTTP %d: %s) — "
                        "falling back to espeak for preview.",
                        exc.status_code,
                        exc.detail,
                    )
                    actual_provider = "espeak"
                    used_fallback = True
                    wpm = int(min(450, max(80, 175 * request.speed)))
                    await _synthesize_espeak(
                        message=message,
                        speed=wpm,
                        pitch=50,
                        output_path=tmp_path,
                    )

        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Provider '{provider}' is not supported for browser preview.",
            )

        # Post-process: apply a lightweight radio static effect for dispatch
        # personas that fell back to local synthesis (i.e. VoxWatch was down).
        # The full radio pipeline (apply_radio_effect in audio_effects.py) is
        # only available when VoxWatch is running; the ffmpeg filter below is a
        # simplified fallback that keeps the local preview from sounding too clean.
        if request.persona in _DISPATCH_MODES:
            radio_path = tmp_path + ".radio.wav"
            try:
                radio_proc = await asyncio.create_subprocess_exec(
                    "ffmpeg", "-y",
                    # Input 0: the clean TTS voice
                    "-i", tmp_path,
                    # Input 1: white noise for radio static
                    "-f", "lavfi", "-i", "anoisesrc=d=60:c=white:a=0.02",
                    # Input 2: dispatch activation beep (1kHz, 0.15s)
                    "-f", "lavfi", "-i", "sine=frequency=1000:duration=0.5,volume=0.3",
                    "-filter_complex",
                    # Process voice: narrow bandpass (radio bandwidth), compress,
                    # mix with static noise. Then prepend the dispatch beep.
                    "[0:a]highpass=f=400,lowpass=f=2500,"
                    "compand=.3|.3:1|1:-90/-60|-60/-40|-40/-30|-20/-20:6:0:-90:0.2,"
                    "volume=0.8[voice];"
                    "[1:a]volume=0.15[noise];"
                    "[voice][noise]amix=inputs=2:duration=first:dropout_transition=0[mixed];"
                    "[2:a][mixed]concat=n=2:v=0:a=1[out]",
                    "-map", "[out]",
                    radio_path,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _, stderr_bytes = await asyncio.wait_for(radio_proc.communicate(), timeout=10.0)
                if radio_proc.returncode == 0 and Path(radio_path).exists():
                    # Swap the radio-processed file in
                    Path(tmp_path).unlink(missing_ok=True)
                    Path(radio_path).rename(tmp_path)
                    logger.info("Applied police radio static effect")
                else:
                    stderr_text = stderr_bytes.decode("utf-8", errors="replace")[-300:]
                    logger.warning("Radio effect ffmpeg failed (rc=%s): %s",
                                   radio_proc.returncode, stderr_text)
            except Exception as exc:
                logger.debug("Radio effect post-processing failed: %s — using clean audio", exc)
            finally:
                Path(radio_path).unlink(missing_ok=True)

        elapsed_ms = int((time.monotonic() - t_start) * 1000)

        # Read the WAV into memory and delete the temp file.
        wav_bytes = Path(tmp_path).read_bytes()

        logger.info(
            "Audio preview generated: provider=%s (configured=%s fallback=%s) "
            "persona=%s voice=%s message_len=%d elapsed_ms=%d",
            actual_provider,
            configured_provider,
            used_fallback,
            request.persona,
            request.voice,
            len(message),
            elapsed_ms,
        )

        return StreamingResponse(
            content=iter([wav_bytes]),
            media_type="audio/wav",
            headers={
                "X-Generation-Time": str(elapsed_ms),
                "X-TTS-Provider": actual_provider,
                "X-TTS-Configured": configured_provider,
                "X-TTS-Fallback": "true" if used_fallback else "false",
                "Cache-Control": "no-store",
            },
        )

    finally:
        # Always clean up the temp file, even if an exception was raised.
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pass


# ── TTS provider test endpoint ────────────────────────────────────────────────


class TestTtsProviderRequest(BaseModel):
    """Request body for POST /api/audio/test-tts-provider."""

    provider: str = Field(
        description=(
            "Cloud TTS provider to test: 'elevenlabs', 'openai', or 'cartesia'. "
            "The provider name is case-insensitive."
        )
    )
    api_key: Optional[str] = Field(
        default=None,
        description=(
            "API key to test.  If omitted the key is read from the saved config "
            "(tts.<provider>_api_key in config.yaml).  Pass this field explicitly "
            "to test a new key before saving it to config."
        ),
    )
    voice_id: Optional[str] = Field(
        default=None,
        description=(
            "Optional voice identifier to validate.  Currently unused for the "
            "lightweight connectivity check but reserved for future expansion."
        ),
    )


class TestTtsProviderResult(BaseModel):
    """Result of a TTS provider API connectivity test."""

    ok: bool = Field(description="True if the API key is valid and the provider is reachable")
    message: str = Field(description="Human-readable result or error description")
    latency_ms: int = Field(description="Round-trip time to the provider's API in milliseconds")


@router.post(
    "/test-tts-provider",
    response_model=TestTtsProviderResult,
    summary="Test cloud TTS provider credentials",
    description=(
        "Validates API key access for a cloud TTS provider by making a lightweight "
        "authenticated request (e.g. listing voices or fetching account info). "
        "No audio is synthesized — this is purely a connectivity and auth check. "
        "Supported providers: elevenlabs, openai, cartesia. "
        "If api_key is omitted, the key from tts.<provider>_api_key in config.yaml is used."
    ),
    status_code=status.HTTP_200_OK,
)
async def test_tts_provider(request: TestTtsProviderRequest) -> TestTtsProviderResult:
    """Test connectivity and authentication for a cloud TTS provider.

    Makes the lightest available authenticated API call for each provider:
    - ElevenLabs: GET /v1/user (returns subscription tier and character quota)
    - OpenAI: GET /v1/models (confirms Bearer token is accepted)
    - Cartesia: GET /voices (confirms X-API-Key header is accepted)

    The api_key field is optional: if omitted, the key is resolved from the
    saved config via ``_resolve_cloud_tts_key``, which handles ``${ENV_VAR}``
    token expansion and masked (``***``) values.  Pass api_key explicitly to
    test a new key before persisting it to config.

    Args:
        request: TestTtsProviderRequest with provider name and optional key.

    Returns:
        TestTtsProviderResult with ok, message, and latency_ms fields.
        Always returns HTTP 200 — the ``ok`` field indicates pass/fail so the
        frontend can display a consistent result regardless of auth outcome.
    """
    import time as _time

    start = _time.monotonic()
    provider = request.provider.lower()

    # Resolve the API key: prefer the explicit field, then fall back to config.
    # If the frontend sends a masked placeholder (e.g. "***MASKED***"), ignore
    # it and resolve from the raw config instead.
    api_key = request.api_key
    if not api_key or api_key.startswith("***"):
        key_name_map = {
            "elevenlabs": "elevenlabs_api_key",
            "openai": "openai_api_key",
            "cartesia": "cartesia_api_key",
        }
        key_name = key_name_map.get(provider)
        if key_name:
            api_key = await _resolve_cloud_tts_key(key_name)

    if not api_key:
        return TestTtsProviderResult(
            ok=False,
            message=f"No API key configured for {provider}. "
                    f"Set tts.{provider}_api_key in config.yaml or pass api_key in the request.",
            latency_ms=0,
        )

    try:
        if provider == "elevenlabs":
            # GET /v1/user returns subscription tier and character quota — a
            # lightweight call that confirms both auth and account status.
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    "https://api.elevenlabs.io/v1/user",
                    headers={"xi-api-key": api_key},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    latency_ms = int((_time.monotonic() - start) * 1000)
                    if resp.status == 401:
                        return TestTtsProviderResult(
                            ok=False,
                            message="Invalid ElevenLabs API key (401 Unauthorized).",
                            latency_ms=latency_ms,
                        )
                    if resp.status != 200:
                        return TestTtsProviderResult(
                            ok=False,
                            message=f"ElevenLabs API returned HTTP {resp.status}.",
                            latency_ms=latency_ms,
                        )
                    data = await resp.json()
                    subscription = data.get("subscription", {})
                    tier = subscription.get("tier", "unknown")
                    chars_used = subscription.get("character_count", 0)
                    chars_limit = subscription.get("character_limit", 0)
                    return TestTtsProviderResult(
                        ok=True,
                        message=(
                            f"Connected. Plan: {tier}. "
                            f"Characters: {chars_used:,}/{chars_limit:,} used."
                        ),
                        latency_ms=latency_ms,
                    )

        elif provider == "openai":
            # GET /v1/models confirms the Bearer token is accepted without
            # actually running an inference request.
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    "https://api.openai.com/v1/models",
                    headers={"Authorization": f"Bearer {api_key}"},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    latency_ms = int((_time.monotonic() - start) * 1000)
                    if resp.status == 401:
                        return TestTtsProviderResult(
                            ok=False,
                            message="Invalid OpenAI API key (401 Unauthorized).",
                            latency_ms=latency_ms,
                        )
                    if resp.status != 200:
                        return TestTtsProviderResult(
                            ok=False,
                            message=f"OpenAI API returned HTTP {resp.status}.",
                            latency_ms=latency_ms,
                        )
                    return TestTtsProviderResult(
                        ok=True,
                        message="API key valid. OpenAI connected.",
                        latency_ms=latency_ms,
                    )

        elif provider == "cartesia":
            # GET /voices confirms the X-API-Key header is accepted without
            # triggering a billable synthesis call.
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    "https://api.cartesia.ai/voices",
                    headers={
                        "X-API-Key": api_key,
                        "Cartesia-Version": "2024-06-10",
                    },
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    latency_ms = int((_time.monotonic() - start) * 1000)
                    if resp.status in (401, 403):
                        return TestTtsProviderResult(
                            ok=False,
                            message=f"Invalid Cartesia API key (HTTP {resp.status}).",
                            latency_ms=latency_ms,
                        )
                    if resp.status != 200:
                        return TestTtsProviderResult(
                            ok=False,
                            message=f"Cartesia API returned HTTP {resp.status}.",
                            latency_ms=latency_ms,
                        )
                    return TestTtsProviderResult(
                        ok=True,
                        message="API key valid. Cartesia connected.",
                        latency_ms=latency_ms,
                    )

        else:
            return TestTtsProviderResult(
                ok=False,
                message=(
                    f"Unknown cloud provider: '{provider}'. "
                    "Supported values: elevenlabs, openai, cartesia."
                ),
                latency_ms=0,
            )

    except aiohttp.ClientConnectorError as exc:
        latency_ms = int((_time.monotonic() - start) * 1000)
        logger.warning("test-tts-provider: network error for %s: %s", provider, exc)
        return TestTtsProviderResult(
            ok=False,
            message=f"Network error reaching {provider} API: {exc}",
            latency_ms=latency_ms,
        )
    except asyncio.TimeoutError:
        latency_ms = int((_time.monotonic() - start) * 1000)
        logger.warning("test-tts-provider: timeout for %s", provider)
        return TestTtsProviderResult(
            ok=False,
            message=f"{provider} API did not respond within 10 seconds.",
            latency_ms=latency_ms,
        )
    except Exception as exc:
        latency_ms = int((_time.monotonic() - start) * 1000)
        logger.exception("test-tts-provider: unexpected error for %s", provider)
        return TestTtsProviderResult(
            ok=False,
            message=str(exc),
            latency_ms=latency_ms,
        )


# ── Dispatch intro upload ─────────────────────────────────────────────────────

# Permitted MIME types and magic-byte signatures for uploaded intro audio.
# We validate the file header to reject non-audio content even if the
# browser sends a convincing Content-Type.
_AUDIO_MAGIC: list[tuple[bytes, str]] = [
    (b"RIFF", "WAV"),   # PCM WAV — first 4 bytes
    (b"\xff\xfb", "MP3"),  # MP3 MPEG-1 frame sync
    (b"\xff\xf3", "MP3"),  # MP3 MPEG-2 frame sync
    (b"\xff\xf2", "MP3"),  # MP3 MPEG-2.5 frame sync
    (b"ID3",  "MP3"),   # MP3 with ID3 tag
    (b"OggS", "OGG"),   # Ogg container (Vorbis/Opus)
    (b"fLaC", "FLAC"),  # FLAC
]

# Maximum allowed upload size (10 MB) — plenty for a short intro clip.
_INTRO_UPLOAD_MAX_BYTES = 10 * 1024 * 1024

# Destination path inside the config volume where the custom intro is stored.
# The /config directory is a named Docker volume that persists across restarts.
_INTRO_UPLOAD_DEST = "/config/audio/dispatch_intro.wav"


def _detect_audio_format(header: bytes) -> Optional[str]:
    """Identify the audio format from the first few bytes of a file.

    Checks the file's magic bytes against the known audio signatures.
    Returns the format name string (e.g. "WAV", "MP3") or ``None`` if
    no known signature matches.

    Args:
        header: The first 8 bytes of the file (or as many as are available).

    Returns:
        Format name string on a match, or ``None`` if unrecognised.
    """
    for magic, fmt in _AUDIO_MAGIC:
        if header.startswith(magic):
            return fmt
    return None


@router.post(
    "/upload-intro",
    summary="Upload custom dispatch channel intro audio",
    description=(
        "Accepts a WAV or MP3 file and saves it as the custom dispatch channel intro. "
        "The file is stored at /config/audio/dispatch_intro.wav (persists across "
        "container restarts). Once saved, set response_mode.dispatch.intro_audio to "
        "/config/audio/dispatch_intro.wav in config.yaml to activate it. "
        "No VoxWatch restart required — the file is checked at runtime on each event."
    ),
    responses={
        200: {"description": "File accepted and saved successfully"},
        400: {"description": "Not a recognised audio file (bad magic bytes or too large)"},
        500: {"description": "Server-side I/O error when saving the file"},
    },
    status_code=status.HTTP_200_OK,
)
async def upload_intro_audio(file: UploadFile) -> dict:
    """Accept a multipart audio upload and save it as the dispatch channel intro.

    The upload is validated before writing:

    1. **Size check** — file content is read up to ``_INTRO_UPLOAD_MAX_BYTES``
       (10 MB). Files that exceed this limit are rejected with HTTP 400.
    2. **Magic-byte check** — the first 8 bytes are inspected to confirm the
       upload is a recognised audio container (WAV, MP3, OGG, FLAC).  A
       mismatched ``Content-Type`` header alone is not trusted.

    On success the raw upload bytes are written to
    ``/config/audio/dispatch_intro.wav``.  The config volume ensures the
    file survives container restarts.

    To activate the uploaded file:

    * Set ``response_mode.dispatch.intro_audio`` to
      ``/config/audio/dispatch_intro.wav`` in the dashboard.
    * Or update ``config.yaml`` directly and hot-reload.
    * No VoxWatch restart is needed — ``generate_channel_intro`` reads the
      path at runtime on each detection event.

    Args:
        file: FastAPI ``UploadFile`` from the ``multipart/form-data`` body.
              Must contain a valid audio file (WAV or MP3 recommended).

    Returns:
        Dict with ``{"success": True, "path": ..., "size_bytes": ...,
        "format": ...}`` on success.

    Raises:
        HTTPException 400: If the file exceeds the size limit or fails the
            magic-byte check (not a recognised audio format).
        HTTPException 500: If the destination directory cannot be created or
            the file cannot be written.
    """
    # Read the entire upload into memory to validate and write atomically.
    # Limiting to _INTRO_UPLOAD_MAX_BYTES prevents OOM from giant uploads.
    raw_bytes: bytes = await file.read(_INTRO_UPLOAD_MAX_BYTES + 1)
    if len(raw_bytes) > _INTRO_UPLOAD_MAX_BYTES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"File too large. Maximum allowed size is "
                f"{_INTRO_UPLOAD_MAX_BYTES // (1024 * 1024)} MB."
            ),
        )

    if not raw_bytes:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Uploaded file is empty.",
        )

    # Validate magic bytes — do not trust Content-Type alone.
    fmt = _detect_audio_format(raw_bytes[:8])
    if fmt is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "Uploaded file does not appear to be a recognised audio format. "
                "Please upload a WAV, MP3, OGG, or FLAC file."
            ),
        )

    # Ensure destination directory exists.
    dest_path = Path(_INTRO_UPLOAD_DEST)
    try:
        dest_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.error(
            "upload-intro: cannot create destination directory %s: %s",
            dest_path.parent,
            exc,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=(
                f"Server error: could not create destination directory "
                f"{dest_path.parent}. Check volume mounts."
            ),
        ) from exc

    # Write atomically via a temp file in the same directory, then rename.
    # This prevents a partial write from corrupting an existing good file.
    tmp_dest = dest_path.parent / (dest_path.name + ".tmp")
    try:
        tmp_dest.write_bytes(raw_bytes)
        tmp_dest.rename(dest_path)
    except OSError as exc:
        logger.error("upload-intro: could not write file to %s: %s", dest_path, exc)
        try:
            tmp_dest.unlink(missing_ok=True)
        except OSError:
            pass
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Server error: could not write audio file to {dest_path}.",
        ) from exc

    logger.info(
        "upload-intro: saved %s intro (%d bytes) → %s",
        fmt,
        len(raw_bytes),
        dest_path,
    )

    return {
        "success": True,
        "path": str(dest_path),
        "size_bytes": len(raw_bytes),
        "format": fmt,
        "message": (
            f"Custom intro audio saved ({len(raw_bytes)} bytes). "
            f"Set response_mode.dispatch.intro_audio to {dest_path} to activate it."
        ),
    }


# ── Dispatch intro generate proxy ─────────────────────────────────────────────

# Destination for the cached generated intro — matches the path used by
# generate_channel_intro() in radio_dispatch.py (Priority 2).
_CACHED_INTRO_PATH = "/data/audio/dispatch_intro_cached.wav"


class GenerateIntroRequest(BaseModel):
    """Request body for POST /api/audio/generate-intro."""

    text: str = Field(
        description=(
            "Text to synthesise as the channel intro phrase. "
            "Supports {agency} template token which is substituted with the "
            "configured agency name from the current config. "
            "Example: 'Connecting to {agency} dispatch frequency.'"
        ),
        min_length=1,
        max_length=400,
    )
    provider: Optional[str] = Field(
        default=None,
        description=(
            "TTS provider override: 'kokoro', 'elevenlabs', 'openai', 'cartesia', "
            "'piper', 'espeak'. When omitted, the currently configured provider is used."
        ),
    )
    voice: Optional[str] = Field(
        default=None,
        description=(
            "Provider-specific voice identifier. "
            "When omitted the provider's configured default voice is used."
        ),
    )
    speed: float = Field(
        default=1.0,
        description="Playback speed multiplier (0.25 – 4.0).",
        ge=0.25,
        le=4.0,
    )
    save: bool = Field(
        default=False,
        description=(
            "When true, the generated audio is saved to "
            "/data/audio/dispatch_intro_cached.wav so the live dispatch pipeline "
            "reuses it automatically on the next detection event."
        ),
    )


@router.post(
    "/generate-intro",
    summary="Generate and optionally save a dispatch channel intro",
    description=(
        "Synthesises a dispatch intro phrase using the requested TTS provider and voice, "
        "streams the WAV back for in-browser preview, and optionally saves it to "
        "/data/audio/dispatch_intro_cached.wav for reuse by the live dispatch pipeline. "
        "Proxies to the VoxWatch Preview API (port 8892) which has access to all "
        "local TTS providers. Cloud providers (ElevenLabs, OpenAI, Cartesia) are "
        "handled locally so no VoxWatch service connection is required for cloud TTS."
    ),
    response_class=StreamingResponse,
    responses={
        200: {
            "content": {"audio/wav": {}},
            "description": (
                "Raw WAV audio for browser playback. "
                "X-Intro-Saved header is 'true' when save=true succeeded."
            ),
        },
        400: {"description": "Bad request (empty text, invalid provider)"},
        502: {"description": "Remote TTS server or VoxWatch Preview API error"},
        503: {"description": "Local TTS binary unavailable"},
    },
)
async def generate_intro_audio(request: GenerateIntroRequest) -> StreamingResponse:
    """Generate a dispatch channel intro with the specified TTS provider and voice.

    This endpoint proxies to the VoxWatch Preview API (``POST
    /api/preview/generate-intro``) which runs inside the VoxWatch service
    container and has direct access to local TTS providers (Kokoro, Piper,
    espeak).  If the VoxWatch service is unreachable, cloud providers
    (ElevenLabs, OpenAI, Cartesia) are attempted locally using the dashboard's
    own synthesis helpers.

    When ``save=true`` the VoxWatch service writes the generated audio to
    ``/data/audio/dispatch_intro_cached.wav``.  This file is shared between
    the VoxWatch and Dashboard containers via a Docker volume, so the live
    dispatch pipeline (``generate_channel_intro`` Priority 2) picks it up
    automatically on the next detection event — no config change or restart
    needed.

    The ``{agency}`` token in ``text`` is substituted on the VoxWatch side
    using the currently saved agency config.

    Args:
        request: GenerateIntroRequest with text, provider, voice, speed, save.

    Returns:
        StreamingResponse with WAV audio and headers:
        - ``X-Generation-Time``: synthesis latency in milliseconds.
        - ``X-Intro-Saved``: "true" when save=true and the file was written.

    Raises:
        400: If text is empty or provider is unsupported.
        502: If the remote TTS API returned an error.
        503: If the required local TTS binary is not installed.
    """
    # Attempt to proxy to VoxWatch Preview API first (handles all local TTS).
    # _get_voxwatch_preview_url() returns "http://host:port/api/preview" —
    # we derive the generate-intro URL from the same host/port.
    voxwatch_preview_url = await _get_voxwatch_preview_url()
    # Strip the trailing endpoint path and append the generate-intro route.
    voxwatch_base = voxwatch_preview_url.rsplit("/api/", 1)[0]
    voxwatch_intro_url = f"{voxwatch_base}/api/preview/generate-intro"

    payload: dict = {
        "text": request.text,
        "speed": request.speed,
        "save": request.save,
    }
    if request.provider:
        payload["provider"] = request.provider
    if request.voice:
        payload["voice"] = request.voice

    t_start = time.monotonic()

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                voxwatch_intro_url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=30.0),
            ) as resp:
                if resp.status == 200:
                    wav_bytes = await resp.read()
                    elapsed_ms = int((time.monotonic() - t_start) * 1000)
                    saved = resp.headers.get("X-Intro-Saved", "false")
                    logger.info(
                        "generate-intro: VoxWatch proxy returned %d bytes "
                        "in %d ms (saved=%s)",
                        len(wav_bytes),
                        elapsed_ms,
                        saved,
                    )
                    return StreamingResponse(
                        content=iter([wav_bytes]),
                        media_type="audio/wav",
                        headers={
                            "X-Generation-Time": str(elapsed_ms),
                            "X-Intro-Saved": saved,
                        },
                    )
                # Non-200 from VoxWatch — fall through to local synthesis.
                body_text = await resp.text()
                logger.warning(
                    "generate-intro: VoxWatch Preview API returned HTTP %d: %s — "
                    "falling back to local cloud synthesis.",
                    resp.status,
                    body_text[:200],
                )
    except (aiohttp.ClientConnectorError, asyncio.TimeoutError) as exc:
        logger.info(
            "generate-intro: VoxWatch Preview API unreachable (%s) — "
            "falling back to local cloud synthesis.",
            exc,
        )
    except Exception as exc:
        logger.warning(
            "generate-intro: VoxWatch proxy error: %s — "
            "falling back to local cloud synthesis.",
            exc,
        )

    # ── Local cloud synthesis fallback ───────────────────────────────────────
    # Substitute {agency} from saved config ourselves since VoxWatch is down.
    intro_text = request.text
    try:
        cfg = await config_service.get_raw_config()
        rm = cfg.get("response_mode", cfg.get("persona", {}))
        agency = rm.get("dispatch", {}).get("agency", "").strip()
        intro_text = request.text.format(agency=agency)
    except (KeyError, ValueError, Exception):
        pass  # Use verbatim on any failure.

    provider = (request.provider or "").lower()

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        if provider == "elevenlabs":
            api_key = await _resolve_cloud_tts_key("elevenlabs_api_key")
            if not api_key:
                raise HTTPException(status_code=400, detail="No ElevenLabs API key configured")
            await _synthesize_elevenlabs(
                message=intro_text,
                api_key=api_key,
                voice_id=request.voice or "pNInz6obpgDQGcFmaJgB",
                model="eleven_flash_v2_5",
                output_path=tmp_path,
            )

        elif provider == "openai":
            api_key = await _resolve_cloud_tts_key("openai_api_key")
            if not api_key:
                raise HTTPException(status_code=400, detail="No OpenAI API key configured")
            await _synthesize_openai_tts(
                message=intro_text,
                api_key=api_key,
                voice=request.voice or "nova",
                model="tts-1",
                speed=request.speed,
                output_path=tmp_path,
            )

        elif provider == "cartesia":
            api_key = await _resolve_cloud_tts_key("cartesia_api_key")
            if not api_key:
                raise HTTPException(status_code=400, detail="No Cartesia API key configured")
            await _synthesize_cartesia(
                message=intro_text,
                api_key=api_key,
                voice_id=request.voice or "",
                output_path=tmp_path,
            )

        elif provider == "espeak":
            wpm = int(min(450, max(80, 175 * request.speed)))
            await _synthesize_espeak(
                message=intro_text,
                speed=wpm,
                pitch=50,
                output_path=tmp_path,
            )

        else:
            # VoxWatch is down and no cloud provider was requested — we cannot
            # serve local TTS providers (Kokoro/Piper) without VoxWatch.
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=(
                    "VoxWatch Preview API is unreachable. "
                    "Local TTS providers (kokoro, piper) require the VoxWatch "
                    "service to be running. Use a cloud provider (elevenlabs, "
                    "openai, cartesia) or start VoxWatch."
                ),
            )

        # Optionally save the generated intro to the shared data volume.
        saved_flag = "false"
        if request.save:
            cached_dir = Path(_CACHED_INTRO_PATH).parent
            try:
                cached_dir.mkdir(parents=True, exist_ok=True)
                import shutil as _shutil
                _shutil.copy2(tmp_path, _CACHED_INTRO_PATH)
                saved_flag = "true"
                logger.info(
                    "generate-intro (local): saved cached intro to %s",
                    _CACHED_INTRO_PATH,
                )
            except OSError as exc:
                logger.warning(
                    "generate-intro (local): could not save to %s: %s — preview OK.",
                    _CACHED_INTRO_PATH,
                    exc,
                )

        elapsed_ms = int((time.monotonic() - t_start) * 1000)
        wav_bytes = Path(tmp_path).read_bytes()

        logger.info(
            "generate-intro (local cloud): provider=%s bytes=%d elapsed_ms=%d saved=%s",
            provider,
            len(wav_bytes),
            elapsed_ms,
            saved_flag,
        )

        return StreamingResponse(
            content=iter([wav_bytes]),
            media_type="audio/wav",
            headers={
                "X-Generation-Time": str(elapsed_ms),
                "X-Intro-Saved": saved_flag,
            },
        )

    finally:
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pass


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _get_stream_name(camera_name: str) -> Optional[str]:
    """Resolve the go2rtc stream name for a camera.

    Resolution order:
      1. VoxWatch config.yaml — the ``go2rtc_stream`` key under the camera
         block, which may differ from the camera name (e.g. if the Frigate
         camera name is "frontdoor" but the go2rtc stream is "frontdoor_hd").
      2. go2rtc streams API — if the camera is not in VoxWatch config (or its
         go2rtc_stream is blank), query go2rtc directly and accept the camera
         name as-is if a matching stream exists.

    Accepting unconfigured cameras allows the test endpoint to verify audio
    on any camera that go2rtc knows about, not just those enrolled in
    VoxWatch.  The go2rtc stream name for Frigate cameras typically matches
    the Frigate camera name verbatim.

    Args:
        camera_name: Camera / stream name to look up.

    Returns:
        Resolved go2rtc stream name string, or None if not found anywhere.
    """
    # --- Step 1: check VoxWatch config ---
    try:
        cfg = await config_service.get_config()
        cam = cfg.get("cameras", {}).get(camera_name, {})
        configured_stream = cam.get("go2rtc_stream") or None
        if configured_stream:
            logger.debug(
                "Resolved stream for %s from config: %s",
                camera_name,
                configured_stream,
            )
            return configured_stream
    except Exception as exc:
        logger.warning("Could not read config for stream lookup of %s: %s", camera_name, exc)

    # --- Step 2: probe go2rtc streams directly ---
    # If the camera is not in VoxWatch config (or has no go2rtc_stream set),
    # check whether go2rtc has a stream whose name matches the camera name.
    # This is the common case for Frigate-managed cameras: Frigate feeds
    # a stream into go2rtc under the same name as the Frigate camera.
    if g2rtc_module.go2rtc_client is not None:
        try:
            streams = await g2rtc_module.go2rtc_client.get_streams()
            if streams and camera_name in streams:
                logger.debug(
                    "Resolved stream for %s directly from go2rtc stream list",
                    camera_name,
                )
                return camera_name
            elif streams is not None:
                logger.debug(
                    "Camera %s not found in go2rtc streams (available: %s)",
                    camera_name,
                    ", ".join(streams.keys()) if streams else "none",
                )
        except Exception as exc:
            logger.warning("go2rtc stream lookup failed for %s: %s", camera_name, exc)

    return None
