"""
audio_preview.py — Audio Preview Endpoint Sub-Router

Handles POST /api/audio/preview — in-browser WAV preview for voice / persona
selection.  All TTS synthesis (Kokoro, Piper, espeak, ElevenLabs, OpenAI,
Cartesia) and the VoxWatch Preview API proxy live here.

For dispatch personas (``police_dispatch``) the request is first proxied to
the VoxWatch Preview API (port 8892) so the full dispatch experience is
generated by the same code that runs during live detection events.  If the
VoxWatch service is unreachable the endpoint falls back to local synthesis so
the user always hears something.

Cloud providers (ElevenLabs, OpenAI, Cartesia) fall back to espeak if their
API key is missing or the call fails.  The X-TTS-Provider, X-TTS-Configured,
and X-TTS-Fallback response headers communicate what actually happened so the
frontend can surface a warning when needed.
"""

import asyncio
import logging
import tempfile
import time
from pathlib import Path

import aiohttp
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from backend.routers._audio_utils import (
    _PIPER_MODEL_RE,
    _get_voxwatch_preview_url,
    _normalize_dispatch_for_tts,
    _resolve_cloud_tts_key,
    _sanitize_tts_message,
)
from backend.services.config_service import config_service

logger = logging.getLogger("dashboard.router.audio.preview")

router = APIRouter()

# ── Constants ─────────────────────────────────────────────────────────────────

# Persona-specific sample messages — one pre-written deterrent per persona so
# the preview sounds realistic without needing a live AI call.
_PERSONA_SAMPLES: dict[str, str] = {
    "standard": (
        "This is the Standard response mode. "
        "Attention. Person in a dark jacket near the side gate. "
        "You are being recorded on camera. Leave the property immediately."
    ),
    "live_operator": (
        "This is the Live Operator response mode. "
        "I can see you at the front door. Step away from the property now."
    ),
    "private_security": (
        "This is the Private Security response mode. "
        "Attention. You are on private property. This area is under 24 hour surveillance. "
        "Leave immediately or authorities will be contacted."
    ),
    "recorded_evidence": (
        "This is the Recorded Evidence response mode. "
        "Subject recorded. Facial capture complete. Entry attempt logged. "
        "Footage has been transmitted to secure storage."
    ),
    "homeowner": (
        "This is the Homeowner response mode. "
        "Hey. I can see you on camera. I don't know who you are, but you need to leave. Now."
    ),
    "automated_surveillance": (
        "This is the Automated Surveillance response mode. "
        "Movement detected. Perimeter zone three. Behavior flagged. "
        "Escalating monitoring level."
    ),
    "police_dispatch": (
        "This is the Police Dispatch response mode. "
        "All units... ten ninety-seven at the residence. "
        "Subject... dark clothing, medium build. "
        "Nearest unit, respond... code three."
    ),
    "neighborhood_watch": (
        "This is the Neighborhood Watch response mode. "
        "Attention, this is a neighborhood watch advisory. "
        "An unidentified individual has been observed approaching this property. "
        "Community patrol and local authorities have been notified."
    ),
    "guard_dog": (
        "This is the Guard Dog Warning response mode. "
        "Hey. I see you on camera. Just so you know, the dogs haven't been fed yet today. "
        "I can let them out if you'd like to stay."
    ),
}

# Default message used when no persona match is found (catches custom personas).
_DEFAULT_SAMPLE = (
    "This is a custom response mode preview. "
    "Attention. This property is under active surveillance. "
    "You have been identified on camera. Please leave the area immediately."
)

#: Response modes that route through the VoxWatch Preview API.
#: Mirrors DISPATCH_MODES in voxwatch/radio_dispatch.py.
_DISPATCH_MODES: frozenset[str] = frozenset({"police_dispatch"})

#: Timeout (seconds) for the VoxWatch preview proxy call.
#: Dispatch previews can take 5-10 s (multiple TTS round-trips + ffmpeg concat).
_VOXWATCH_PROXY_TIMEOUT = 60.0


# ── Request model ─────────────────────────────────────────────────────────────


class PreviewRequest(BaseModel):
    """Request body for POST /api/audio/preview."""

    persona: str = Field(
        default="standard",
        description="Persona name from the PERSONAS dict (e.g. 'private_security', 'police_dispatch').",
    )
    voice: str = Field(
        default="af_heart",
        description="TTS voice identifier (Kokoro voice ID, Piper model name, etc.).",
    )
    provider: str = Field(
        default="kokoro",
        description="TTS provider name: 'kokoro', 'piper', 'espeak'.",
    )
    provider_host: str | None = Field(
        default=None,
        description=(
            "Base URL of the remote TTS server (e.g. 'http://kokoro-server:8880'). "
            "Required for Kokoro remote. Ignored for piper/espeak."
        ),
    )
    message: str | None = Field(
        default=None,
        description=(
            "Custom message text to synthesize. "
            "If omitted a realistic deterrent sample is generated from the persona."
        ),
        max_length=500,
    )
    speed: float = Field(
        default=1.0,
        description="Playback speed multiplier (0.5 – 2.0).",
        ge=0.25,
        le=4.0,
    )


# ── Private helpers ───────────────────────────────────────────────────────────


def _sample_for_persona(persona: str) -> str:
    """Return a realistic deterrent sample message for the given persona name.

    Prefers the exact persona key.  Falls back to the generic default so
    custom persona names don't blow up.

    Args:
        persona: Persona key string (e.g. "private_security", "police_dispatch").

    Returns:
        Sample deterrent message string, ready to pass to a TTS provider.
    """
    return _PERSONA_SAMPLES.get(persona, _DEFAULT_SAMPLE)


async def _personalize_dispatch_sample(message: str) -> str:
    """Replace generic dispatch sample text with configured address/agency.

    Reads the saved config for dispatch settings and injects them into
    the sample message so the preview sounds like the real thing.

    Args:
        message: The dispatch sample text.

    Returns:
        Personalized message with address/agency if configured.
    """
    try:
        cfg = await config_service.get_raw_config()
        rm = cfg.get("response_mode", cfg.get("persona", {}))
        dispatch = rm.get("dispatch", {})

        address = dispatch.get("full_address", "").strip()
        agency = dispatch.get("agency", "").strip()
        callsign = dispatch.get("callsign", "").strip()

        if address:
            # Build a personalized sample
            agency_prefix = f"{agency} dispatch. " if agency else ""
            callsign_suffix = f" {callsign}, respond code 3." if callsign else " Requesting unit respond."
            return (
                f"{agency_prefix}All units, 10-31 in progress at {address}. "
                f"Suspect described as male, dark hoodie, carrying backpack, "
                f"approaching front entrance.{callsign_suffix} "
                f"Subject is on camera."
            )
    except Exception:
        pass
    return message


async def _proxy_dispatch_preview(
    request: "PreviewRequest",
) -> tuple[bytes, dict[str, str]] | None:
    """Proxy a preview request to the VoxWatch Preview API.

    Forwards the preview request body to the VoxWatch service on port 8892 and
    returns the raw WAV bytes along with provider tracking headers from the
    VoxWatch response.

    Args:
        request: The dashboard ``PreviewRequest`` model populated by the browser.

    Returns:
        Tuple of (wav_bytes, headers_dict) from the VoxWatch Preview API, or
        ``None`` if the request could not be completed.
    """
    url = await _get_voxwatch_preview_url()

    payload: dict = {
        "response_mode": request.persona,
        "voice": request.voice,
        "provider": request.provider,
        "speed": request.speed,
    }
    if request.message:
        payload["message"] = request.message

    logger.debug(
        "Proxying preview to VoxWatch Preview API: %s mode=%s provider=%s",
        url,
        request.persona,
        request.provider,
    )

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=_VOXWATCH_PROXY_TIMEOUT),
            ) as resp:
                if resp.status != 200:
                    body_text = await resp.text()
                    logger.warning(
                        "VoxWatch Preview API returned HTTP %d for preview: %s",
                        resp.status,
                        body_text[:200],
                    )
                    return None

                # Forward provider tracking headers from VoxWatch.
                proxy_headers = {
                    "X-Generation-Time-Ms": resp.headers.get("X-Generation-Time-Ms", "0"),
                    "X-TTS-Provider": resp.headers.get("X-TTS-Provider", request.provider),
                    "X-TTS-Configured": resp.headers.get("X-TTS-Configured", request.provider),
                    "X-TTS-Fallback": resp.headers.get("X-TTS-Fallback", "false"),
                }
                fallback_reason = resp.headers.get("X-TTS-Fallback-Reason", "")
                if fallback_reason:
                    proxy_headers["X-TTS-Fallback-Reason"] = fallback_reason
                elapsed_ms = proxy_headers["X-Generation-Time-Ms"]
                logger.info(
                    "Preview received from VoxWatch: %s ms, mode=%s provider=%s",
                    elapsed_ms,
                    request.persona,
                    proxy_headers["X-TTS-Provider"],
                )
                wav_bytes = await resp.read()
                return (wav_bytes, proxy_headers)

    except aiohttp.ClientConnectorError as exc:
        logger.info(
            "VoxWatch Preview API unreachable at %s (%s) — falling back to local synthesis.",
            url,
            exc,
        )
        return None
    except TimeoutError:
        logger.warning(
            "VoxWatch Preview API timed out after %.0fs — falling back to local synthesis.",
            _VOXWATCH_PROXY_TIMEOUT,
        )
        return None
    except Exception as exc:
        logger.warning(
            "VoxWatch Preview API proxy error: %s — falling back to local synthesis.",
            exc,
        )
        return None


# ── TTS synthesis helpers ─────────────────────────────────────────────────────


async def _synthesize_kokoro(
    message: str,
    voice: str,
    speed: float,
    host: str,
    output_path: str,
) -> None:
    """POST to a Kokoro TTS HTTP server and write the WAV response to disk.

    Kokoro's /tts endpoint accepts a JSON body and returns raw PCM/WAV audio.
    The VoxWatch kokoro_provider.py uses the same protocol — this function
    replicates that call so the preview endpoint doesn't need to import the
    full TTS provider machinery.

    Args:
        message:     Text to synthesize.
        voice:       Kokoro voice ID (e.g. "af_heart").
        speed:       Playback speed multiplier.
        host:        Base URL of the Kokoro HTTP server.
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 502: If the Kokoro server is unreachable or returns an error.
    """
    url = f"{host.rstrip('/')}/tts"
    payload = {"text": message, "voice": voice, "speed": speed}

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                url,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise HTTPException(
                        status_code=status.HTTP_502_BAD_GATEWAY,
                        detail=(
                            f"Kokoro server returned HTTP {resp.status}: {body[:200]}"
                        ),
                    )
                audio_bytes = await resp.read()

        Path(output_path).write_bytes(audio_bytes)

    except aiohttp.ClientError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Cannot reach Kokoro server at {host}: {exc}",
        ) from exc


async def _synthesize_piper(
    message: str,
    model: str,
    speed: float,
    output_path: str,
) -> None:
    """Run piper TTS via subprocess and write the WAV output to disk.

    Piper is invoked as ``piper --model <model> --output_file <path>`` with the
    message piped through stdin.  The model baked into the Docker image is used;
    the ``model`` argument is passed as-is so the preview respects whatever model
    the user has configured.

    Args:
        message:     Text to synthesize.
        model:       Piper model name (e.g. "en_US-lessac-medium").
        speed:       Length scale (1.0 = normal; piper uses length_scale inverse).
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 500: If piper exits with a non-zero return code.
        HTTPException 503: If the piper binary is not found.
    """
    # piper uses --length_scale as the inverse of speed: 1/speed gives the
    # correct duration scaling.  Clamp to avoid extreme values.
    length_scale = round(1.0 / max(speed, 0.25), 3)
    cmd = [
        "piper",
        "--model", model,
        "--length_scale", str(length_scale),
        "--output_file", output_path,
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await asyncio.wait_for(
            proc.communicate(input=message.encode()),
            timeout=30.0,
        )

        if proc.returncode != 0:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"piper exited with code {proc.returncode}: {stderr.decode()[:300]}",
            )

    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="piper binary not found. Ensure piper is installed in the Docker image.",
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="piper synthesis timed out after 30 seconds.",
        )


async def _synthesize_espeak(
    message: str,
    speed: int,
    pitch: int,
    output_path: str,
) -> None:
    """Run espeak-ng via subprocess and write the WAV output to disk.

    espeak-ng is the always-available last-resort fallback.  It is invoked
    as ``espeak-ng -s <speed> -p <pitch> -w <output_path>`` with the message
    passed as the final argument.

    Args:
        message:     Text to synthesize.
        speed:       Words-per-minute rate (80 – 450).
        pitch:       Voice pitch (0 – 99).
        output_path: Absolute path to write the WAV file.

    Raises:
        HTTPException 503: If espeak-ng is not installed.
        HTTPException 500: On subprocess failure.
    """
    cmd = [
        "espeak-ng",
        "-s", str(speed),
        "-p", str(pitch),
        "-w", output_path,
        "--", message,
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await asyncio.wait_for(
            proc.communicate(),
            timeout=15.0,
        )

        if proc.returncode != 0:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"espeak-ng exited with code {proc.returncode}: {stderr.decode()[:300]}",
            )

    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="espeak-ng binary not found. Install espeak-ng in the Docker image.",
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="espeak-ng synthesis timed out after 15 seconds.",
        )


async def _synthesize_elevenlabs(
    message: str, api_key: str, voice_id: str, model: str, output_path: str,
) -> None:
    """Synthesize audio using ElevenLabs API via raw HTTP.

    No SDK required — uses aiohttp to POST to the text-to-speech endpoint
    and saves the returned audio bytes.

    Args:
        message: Text to synthesize.
        api_key: ElevenLabs API key.
        voice_id: Voice ID from ElevenLabs voice library.
        model: Model name (e.g. "eleven_flash_v2_5").
        output_path: Where to write the output audio file.
    """
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "audio/mpeg",
    }
    payload = {
        "text": message,
        "model_id": model,
        # High stability = monotone, flat delivery (how real dispatchers sound).
        # Low similarity_boost = less voice cloning artifacts.
        # style = 0 removes expressive/emotional inflection entirely.
        "voice_settings": {
            "stability": 1.0,
            "similarity_boost": 0.3,
            "style": 0.0,
            "use_speaker_boost": False,
        },
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status == 401:
                raise HTTPException(status_code=400, detail="Invalid ElevenLabs API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"ElevenLabs error: {body[:200]}")
            audio_data = await resp.read()

    # ElevenLabs returns MP3 — convert to WAV for browser playback
    proc = await asyncio.create_subprocess_exec(
        "ffmpeg", "-y", "-i", "pipe:0", "-f", "wav", output_path,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    _, stderr_data = await proc.communicate(input=audio_data)
    if proc.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail=f"Audio conversion failed: {stderr_data.decode('utf-8', errors='replace')[-200:]}",
        )


async def _synthesize_openai_tts(
    message: str, api_key: str, voice: str, model: str, speed: float,
    output_path: str,
) -> None:
    """Synthesize audio using OpenAI TTS API via raw HTTP.

    Args:
        message: Text to synthesize.
        api_key: OpenAI API key.
        voice: Voice name (alloy, echo, fable, onyx, nova, shimmer).
        model: Model (tts-1 or tts-1-hd).
        speed: Speed multiplier (0.25-4.0).
        output_path: Where to write the output audio file.
    """
    url = "https://api.openai.com/v1/audio/speech"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "input": message,
        "voice": voice,
        "speed": max(0.25, min(4.0, speed)),
        "response_format": "wav",
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status == 401:
                raise HTTPException(status_code=400, detail="Invalid OpenAI API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"OpenAI TTS error: {body[:200]}")
            audio_data = await resp.read()

    with open(output_path, "wb") as f:
        f.write(audio_data)


async def _synthesize_cartesia(
    message: str, api_key: str, voice_id: str, output_path: str,
) -> None:
    """Synthesize audio using Cartesia Sonic API via raw HTTP.

    Args:
        message: Text to synthesize.
        api_key: Cartesia API key.
        voice_id: Cartesia voice ID.
        output_path: Where to write the output audio file.
    """
    url = "https://api.cartesia.ai/tts/bytes"
    headers = {
        "X-API-Key": api_key,
        "Cartesia-Version": "2024-06-10",
        "Content-Type": "application/json",
    }
    payload = {
        "transcript": message,
        "model_id": "sonic-english",
        "voice": {"mode": "id", "id": voice_id} if voice_id else {"mode": "id", "id": "a0e99841-438c-4a64-b679-ae501e7d6091"},
        "output_format": {"container": "wav", "encoding": "pcm_f32le", "sample_rate": 44100},
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload, headers=headers,
                                timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status in (401, 403):
                raise HTTPException(status_code=400, detail="Invalid Cartesia API key")
            if resp.status != 200:
                body = await resp.text()
                raise HTTPException(status_code=502, detail=f"Cartesia error: {body[:200]}")
            audio_data = await resp.read()

    with open(output_path, "wb") as f:
        f.write(audio_data)


# ── espeak fallback helper (R4) ───────────────────────────────────────────────


async def _try_with_espeak_fallback(
    synthesize_fn,
    message: str,
    speed: float,
    output_path: str,
    tmp_path: str,
    provider_name: str,
) -> tuple[str, bool]:
    """Try a cloud provider, falling back to espeak on failure.

    Attempts ``synthesize_fn`` (a coroutine that writes audio to
    ``output_path``).  If the call raises an ``HTTPException`` the error is
    logged and espeak is invoked instead as a last-resort fallback so the
    user always hears something.

    Args:
        synthesize_fn: Async callable that synthesizes audio to ``output_path``.
                       Must be a zero-argument coroutine (close over args via
                       ``functools.partial`` or a lambda).
        message:       TTS input text (used for the espeak fallback).
        speed:         Speed multiplier (used to compute espeak WPM).
        output_path:   Destination path for the audio file.
        tmp_path:      Same path as output_path — kept as a named parameter
                       for clarity; the espeak call writes here on fallback.
        provider_name: Human-readable provider label used in log messages.

    Returns:
        Tuple of ``(actual_provider, used_fallback)`` where ``actual_provider``
        is either ``provider_name`` (success) or ``"espeak"`` (fallback), and
        ``used_fallback`` is ``True`` when espeak was substituted.
    """
    try:
        await synthesize_fn()
        return (provider_name, False)
    except HTTPException as exc:
        logger.warning(
            "%s synthesis failed (HTTP %d: %s) — falling back to espeak for preview.",
            provider_name,
            exc.status_code,
            exc.detail,
        )
        wpm = int(min(450, max(80, 175 * speed)))
        await _synthesize_espeak(
            message=message,
            speed=wpm,
            pitch=50,
            output_path=tmp_path,
        )
        return ("espeak", True)


# ── Endpoint ──────────────────────────────────────────────────────────────────


@router.post(
    "/preview",
    summary="Generate browser-playable audio preview",
    description=(
        "Synthesizes a deterrent message using the specified TTS provider and persona, "
        "then returns the raw WAV audio for in-browser playback. "
        "No camera speaker is involved — this is a pure preview for voice selection. "
        "Supported providers: kokoro (remote HTTP server), piper (local), espeak (local fallback). "
        "Response headers X-TTS-Provider, X-TTS-Configured, and X-TTS-Fallback indicate which "
        "provider actually generated the audio and whether a fallback occurred."
    ),
    response_class=StreamingResponse,
    responses={
        200: {
            "content": {"audio/wav": {}},
            "description": "Raw WAV audio. Play with: new Audio(URL.createObjectURL(blob))",
            "headers": {
                "X-Generation-Time": {
                    "description": "Synthesis latency in milliseconds",
                    "schema": {"type": "string"},
                },
                "X-TTS-Provider": {
                    "description": "TTS provider that actually generated the audio",
                    "schema": {"type": "string"},
                },
                "X-TTS-Configured": {
                    "description": "TTS provider that was requested/configured",
                    "schema": {"type": "string"},
                },
                "X-TTS-Fallback": {
                    "description": "Whether a fallback provider was used ('true' or 'false')",
                    "schema": {"type": "string"},
                },
            },
        },
        400: {"description": "Unsupported provider or bad request"},
        502: {"description": "Remote TTS server error"},
        503: {"description": "Local TTS binary not available"},
    },
)
async def preview_audio(request: PreviewRequest) -> StreamingResponse:
    """Synthesize a deterrent message sample and stream WAV back to the browser.

    The caller selects a persona and TTS provider.  If no custom message is
    supplied, a pre-written sample for that persona is used so the user hears
    a realistic deterrent rather than a bland test phrase.

    Synthesis is performed inside a temporary file so the WAV can be read back
    after the subprocess/HTTP call finishes.  The temp file is deleted after
    the response is streamed.

    For cloud providers (ElevenLabs, OpenAI, Cartesia), if synthesis fails due
    to a missing or invalid API key, the endpoint falls back to espeak rather
    than returning an error, so the user always hears something.  The response
    headers X-TTS-Provider, X-TTS-Configured, and X-TTS-Fallback communicate
    what actually happened so the frontend can surface a warning if needed.

    Args:
        request: PreviewRequest with persona, voice, provider, optional message,
                 and speed.

    Returns:
        StreamingResponse with Content-Type audio/wav and headers:
        - X-Generation-Time: synthesis latency in milliseconds.
        - X-TTS-Provider: provider that actually generated the audio.
        - X-TTS-Configured: provider that was requested/configured.
        - X-TTS-Fallback: "true" if a fallback provider was used, "false" otherwise.

    Raises:
        400: If provider is unsupported (cloud providers that need full factory machinery).
        502: If the remote Kokoro server is unreachable or returns an error.
        503: If a required local binary (piper, espeak-ng) is not installed.
        504: If synthesis exceeds the timeout.
    """
    # Track which provider was requested and which actually ran, so the headers
    # can accurately reflect whether a fallback occurred.
    configured_provider = request.provider.lower()
    actual_provider = configured_provider
    used_fallback = False

    # ── Proxy to VoxWatch Preview API when needed ────────────────────────────
    # ALL preview requests proxy to the VoxWatch service first.  The
    # dashboard container has no TTS binaries (no espeak, piper, ffmpeg) —
    # only the VoxWatch container has the full AudioPipeline.  Cloud-only
    # providers (ElevenLabs, OpenAI, Cartesia) could technically run here
    # but routing everything through one path keeps voice resolution and
    # fallback behavior consistent.  If VoxWatch is unreachable, we fall
    # through to local cloud-only synthesis as a last resort.
    _should_proxy = True
    if _should_proxy:
        t_proxy_start = time.monotonic()
        proxy_result = await _proxy_dispatch_preview(request)
        if proxy_result is not None:
            wav_bytes, proxy_headers = proxy_result
            elapsed_ms = int((time.monotonic() - t_proxy_start) * 1000)
            logger.info(
                "Preview proxied from VoxWatch: persona=%s provider=%s fallback=%s elapsed_ms=%d bytes=%d",
                request.persona,
                proxy_headers.get("X-TTS-Provider", "?"),
                proxy_headers.get("X-TTS-Fallback", "false"),
                elapsed_ms,
                len(wav_bytes),
            )
            resp_headers = {
                "X-Generation-Time": str(elapsed_ms),
                "X-TTS-Provider": proxy_headers.get("X-TTS-Provider", configured_provider),
                "X-TTS-Configured": proxy_headers.get("X-TTS-Configured", configured_provider),
                "X-TTS-Fallback": proxy_headers.get("X-TTS-Fallback", "false"),
                "X-VoxWatch-Proxy": "proxied",
                "Cache-Control": "no-store",
            }
            # Forward the fallback reason so the frontend can display it.
            fallback_reason = proxy_headers.get("X-TTS-Fallback-Reason", "")
            if fallback_reason:
                resp_headers["X-TTS-Fallback-Reason"] = fallback_reason
            return StreamingResponse(
                content=iter([wav_bytes]),
                media_type="audio/wav",
                headers=resp_headers,
            )
        # VoxWatch unreachable — fall through to local synthesis so the user
        # still hears something (plain TTS without the full dispatch experience).
        logger.info(
            "Dispatch preview falling back to local synthesis for persona=%s",
            request.persona,
        )

    # Resolve the message — prefer the caller's custom text, then persona sample.
    message = (request.message or "").strip() or _sample_for_persona(request.persona)
    # Strip Unicode control characters before passing to any TTS subprocess.
    message = _sanitize_tts_message(message)

    # Validate piper model name if the provider is piper — prevent path traversal
    # in the --model argument even though create_subprocess_exec is shell-safe.
    if configured_provider == "piper" and request.voice and not _PIPER_MODEL_RE.match(request.voice):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid Piper model name. Only alphanumeric, hyphens, and underscores allowed.",
        )

    # For dispatch personas that fell back to local synthesis, personalize with
    # configured address/agency and normalize 10-codes to spoken form for TTS.
    if request.persona in _DISPATCH_MODES:
        message = await _personalize_dispatch_sample(message)
        message = _normalize_dispatch_for_tts(message)

    t_start = time.monotonic()

    # Use a temp file for the WAV output.  The file is created here and cleaned
    # up after we read it back; NamedTemporaryFile with delete=False is used so
    # the subprocess can write to it by path on all platforms.
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        provider = request.provider.lower()

        if provider == "kokoro":
            # Kokoro requires a host URL.  Fall back to reading from config if
            # the caller didn't supply one (so users who have it saved in config
            # don't need to re-enter it).
            host = request.provider_host
            if not host:
                try:
                    cfg = await config_service.get_config()
                    host = cfg.get("tts", {}).get("kokoro_host") or None
                except Exception:
                    host = None

            if not host:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=(
                        "Kokoro host URL is required for preview. "
                        "Set it in TTS config or pass provider_host in the request."
                    ),
                )

            await _synthesize_kokoro(
                message=message,
                voice=request.voice,
                speed=request.speed,
                host=host,
                output_path=tmp_path,
            )

        elif provider == "piper":
            # voice field doubles as the model name for piper.
            # Piper runs inside the VoxWatch container, not the dashboard.
            # If piper isn't available here, fall back to espeak for preview.
            model = request.voice or "en_US-lessac-medium"
            try:
                await _synthesize_piper(
                    message=message,
                    model=model,
                    speed=request.speed,
                    output_path=tmp_path,
                )
            except HTTPException as exc:
                if exc.status_code == 503:
                    # Piper not installed in this container — use espeak fallback
                    logger.info(
                        "Piper not available in dashboard container, "
                        "falling back to espeak for preview"
                    )
                    actual_provider = "espeak"
                    used_fallback = True
                    wpm = int(min(450, max(80, 175 * request.speed)))
                    await _synthesize_espeak(
                        message=message,
                        speed=wpm,
                        pitch=50,
                        output_path=tmp_path,
                    )
                else:
                    raise

        elif provider == "espeak":
            # Speed for espeak is words-per-minute, not a multiplier.
            # Convert: 1.0 = 175 WPM (piper/kokoro normal), scale linearly.
            wpm = int(min(450, max(80, 175 * request.speed)))
            await _synthesize_espeak(
                message=message,
                speed=wpm,
                pitch=50,
                output_path=tmp_path,
            )

        elif provider == "elevenlabs":
            # Attempt ElevenLabs synthesis.  If the API key is missing or the
            # call fails, fall back to espeak so the user hears something and
            # the headers explain what happened.
            api_key = await _resolve_cloud_tts_key("elevenlabs_api_key")
            if not api_key:
                logger.warning(
                    "ElevenLabs API key not configured — falling back to espeak for preview. "
                    "Set tts.elevenlabs_api_key in config.yaml to enable ElevenLabs preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                actual_provider, used_fallback = await _try_with_espeak_fallback(
                    synthesize_fn=lambda: _synthesize_elevenlabs(
                        message=message,
                        api_key=api_key,
                        voice_id=request.voice or "pNInz6obpgDQGcFmaJgB",
                        model="eleven_flash_v2_5",
                        output_path=tmp_path,
                    ),
                    message=message,
                    speed=request.speed,
                    output_path=tmp_path,
                    tmp_path=tmp_path,
                    provider_name="elevenlabs",
                )

        elif provider == "openai":
            # Same fallback pattern as ElevenLabs.
            api_key = await _resolve_cloud_tts_key("openai_api_key")
            if not api_key:
                logger.warning(
                    "OpenAI API key not configured — falling back to espeak for preview. "
                    "Set tts.openai_api_key in config.yaml to enable OpenAI TTS preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                actual_provider, used_fallback = await _try_with_espeak_fallback(
                    synthesize_fn=lambda: _synthesize_openai_tts(
                        message=message,
                        api_key=api_key,
                        voice=request.voice or "onyx",
                        model="tts-1",
                        speed=request.speed,
                        output_path=tmp_path,
                    ),
                    message=message,
                    speed=request.speed,
                    output_path=tmp_path,
                    tmp_path=tmp_path,
                    provider_name="openai",
                )

        elif provider == "cartesia":
            # Same fallback pattern as ElevenLabs.
            api_key = await _resolve_cloud_tts_key("cartesia_api_key")
            if not api_key:
                logger.warning(
                    "Cartesia API key not configured — falling back to espeak for preview. "
                    "Set tts.cartesia_api_key in config.yaml to enable Cartesia preview."
                )
                actual_provider = "espeak"
                used_fallback = True
                wpm = int(min(450, max(80, 175 * request.speed)))
                await _synthesize_espeak(
                    message=message,
                    speed=wpm,
                    pitch=50,
                    output_path=tmp_path,
                )
            else:
                actual_provider, used_fallback = await _try_with_espeak_fallback(
                    synthesize_fn=lambda: _synthesize_cartesia(
                        message=message,
                        api_key=api_key,
                        voice_id=request.voice or "",
                        output_path=tmp_path,
                    ),
                    message=message,
                    speed=request.speed,
                    output_path=tmp_path,
                    tmp_path=tmp_path,
                    provider_name="cartesia",
                )

        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Provider '{provider}' is not supported for browser preview.",
            )

        # Post-process: apply a lightweight radio static effect for dispatch
        # personas that fell back to local synthesis (i.e. VoxWatch was down).
        # The full radio pipeline (apply_radio_effect in audio_effects.py) is
        # only available when VoxWatch is running; the ffmpeg filter below is a
        # simplified fallback that keeps the local preview from sounding too clean.
        if request.persona in _DISPATCH_MODES:
            radio_path = tmp_path + ".radio.wav"
            try:
                radio_proc = await asyncio.create_subprocess_exec(
                    "ffmpeg", "-y",
                    # Input 0: the clean TTS voice
                    "-i", tmp_path,
                    # Input 1: white noise for radio static
                    "-f", "lavfi", "-i", "anoisesrc=d=60:c=white:a=0.02",
                    # Input 2: dispatch activation beep (1kHz, 0.15s)
                    "-f", "lavfi", "-i", "sine=frequency=1000:duration=0.5,volume=0.3",
                    "-filter_complex",
                    # Process voice: narrow bandpass (radio bandwidth), compress,
                    # mix with static noise. Then prepend the dispatch beep.
                    "[0:a]highpass=f=400,lowpass=f=2500,"
                    "compand=.3|.3:1|1:-90/-60|-60/-40|-40/-30|-20/-20:6:0:-90:0.2,"
                    "volume=0.8[voice];"
                    "[1:a]volume=0.15[noise];"
                    "[voice][noise]amix=inputs=2:duration=first:dropout_transition=0[mixed];"
                    "[2:a][mixed]concat=n=2:v=0:a=1[out]",
                    "-map", "[out]",
                    radio_path,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _, stderr_bytes = await asyncio.wait_for(radio_proc.communicate(), timeout=10.0)
                if radio_proc.returncode == 0 and Path(radio_path).exists():
                    # Swap the radio-processed file in
                    Path(tmp_path).unlink(missing_ok=True)
                    Path(radio_path).rename(tmp_path)
                    logger.info("Applied police radio static effect")
                else:
                    stderr_text = stderr_bytes.decode("utf-8", errors="replace")[-300:]
                    logger.warning("Radio effect ffmpeg failed (rc=%s): %s",
                                   radio_proc.returncode, stderr_text)
            except Exception as exc:
                logger.debug("Radio effect post-processing failed: %s — using clean audio", exc)
            finally:
                Path(radio_path).unlink(missing_ok=True)

        elapsed_ms = int((time.monotonic() - t_start) * 1000)

        # Read the WAV into memory and delete the temp file.
        wav_bytes = Path(tmp_path).read_bytes()

        logger.info(
            "Audio preview generated: provider=%s (configured=%s fallback=%s) "
            "persona=%s voice=%s message_len=%d elapsed_ms=%d",
            actual_provider,
            configured_provider,
            used_fallback,
            request.persona,
            request.voice,
            len(message),
            elapsed_ms,
        )

        return StreamingResponse(
            content=iter([wav_bytes]),
            media_type="audio/wav",
            headers={
                "X-Generation-Time": str(elapsed_ms),
                "X-TTS-Provider": actual_provider,
                "X-TTS-Configured": configured_provider,
                "X-TTS-Fallback": "true" if used_fallback else "false",
                "X-VoxWatch-Proxy": "local-fallback",
                "Cache-Control": "no-store",
            },
        )

    finally:
        # Always clean up the temp file, even if an exception was raised.
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pass
