"""
tts/__init__.py — VoxWatch Multi-Provider TTS Sub-Package

Exposes the public API surface for the TTS layer.  Callers should import
from this module rather than reaching into provider sub-modules directly.

Quick start:
    from voxwatch.tts import generate_with_fallback, TTSResult

    result = await generate_with_fallback(
        message="You are on camera.",
        output_path="/data/audio/stage1_tts.wav",
        config=config,
    )
    print(f"Generated by {result.provider_name} in {result.duration_seconds:.1f}s")

For more control (pre-warmed providers, explicit fallback chain):
    from voxwatch.tts import get_provider, get_fallback_chain

    provider = get_provider(config)
    await provider.warmup()
    result = await provider.generate(message, output_path)
"""

from voxwatch.tts.base import TTSProvider, TTSProviderError, TTSResult
from voxwatch.tts.factory import generate_with_fallback, get_fallback_chain, get_provider

__all__ = [
    # Core types
    "TTSResult",
    "TTSProviderError",
    "TTSProvider",
    # Factory functions
    "get_provider",
    "get_fallback_chain",
    "generate_with_fallback",
]
